version: "2"

linters:
  default: none
  enable:
    - govet
    - bodyclose
    - durationcheck
    - nilnesserr
    - sqlclosecheck
    - gocheckcompilerdirectives
    - nolintlint
    - errorlint
    - nilerr
    - nilnil
    - rowserrcheck
    - wastedassign
    - errcheck
    - unused
    - ineffassign
    - gosec
    - staticcheck
    - exhaustive
    - musttag
    - canonicalheader
    - recvcheck
    - noctx
    - dupl
    - interfacebloat
    - gocognit
    - testifylint

  settings:
    gocognit:
      min-complexity: 70
    interfacebloat:
      max: 10
    errcheck:
      check-blank: true
      check-type-assertions: true
    nolintlint:
      require-explanation: true
      require-specific: true
    staticcheck:
      checks:
        - SA*
    testifylint:
      disable-all: true
      enable:
        - error-nil
        - require-error

  exclusions:
    generated: strict
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - gocognit

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  build-tags:
    - integration
  tests: true
