package batchvalidation

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/justin-hayes/mouseion/internal/enrichment"
)

func loadTestFixture(t *testing.T) (Fixture, []byte) {
	t.Helper()
	files := ReadDefaultFiles("testdata")
	fixture, requests, err := LoadFixture(files)
	if err != nil {
		t.Fatal(err)
	}
	return fixture, requests
}

func TestFrozenFixtureReplaysBothTransportsWithStableArtifacts(t *testing.T) {
	fixture, frozenRequests := loadTestFixture(t)
	codec, err := enrichment.NewTranslationCodec(enrichment.LLMConfig{Model: fixture.Model})
	if err != nil {
		t.Fatal(err)
	}
	syncResult, batchResult, err := ReplayFixedResponses(context.Background(), codec, fixture, frozenRequests, DefaultRunID, DefaultGeneration)
	if err != nil {
		t.Fatal(err)
	}
	if syncResult.Artifact != batchResult.Artifact {
		t.Fatalf("fixed-response artifacts differ: sync=%+v batch=%+v", syncResult.Artifact, batchResult.Artifact)
	}
	if syncResult.Metrics.CacheHits != 1 || syncResult.Metrics.CacheMisses != 2 || batchResult.Metrics.ProviderCalls != 1 || syncResult.Completeness.QualityOmitted != 1 {
		t.Fatalf("unexpected replay metrics: sync=%+v batch=%+v", syncResult.Metrics, batchResult.Metrics)
	}
	if !syncResult.ArtifactStable || !batchResult.ArtifactStable || syncResult.Quality.TargetAligned != batchResult.Quality.TargetAligned {
		t.Fatalf("replay is not stable/aligned: sync=%+v batch=%+v", syncResult, batchResult)
	}
}

func TestFrozenRequestFixtureRejectsSemanticDrift(t *testing.T) {
	fixture, frozenRequests := loadTestFixture(t)
	codec, err := enrichment.NewTranslationCodec(enrichment.LLMConfig{Model: fixture.Model})
	if err != nil {
		t.Fatal(err)
	}
	changed := bytes.Replace(frozenRequests, []byte(`"model":"gpt-test"`), []byte(`"model":"different-model"`), 1)
	if _, _, err = ReplayFixedResponses(context.Background(), codec, fixture, changed, DefaultRunID, DefaultGeneration); err == nil || !strings.Contains(err.Error(), "frozen request fixture") {
		t.Fatalf("semantic request drift was accepted: %v", err)
	}
}

func TestFrozenRequestsMatchExactProviderJSONL(t *testing.T) {
	fixture, frozenRequests := loadTestFixture(t)
	codec, err := enrichment.NewTranslationCodec(enrichment.LLMConfig{Model: fixture.Model})
	if err != nil {
		t.Fatal(err)
	}
	requests, items, err := FrozenRequests(codec, fixture, DefaultRunID, DefaultGeneration)
	if err != nil {
		t.Fatal(err)
	}
	var generated bytes.Buffer
	if _, err = codec.WriteBatchJSONL(&generated, DefaultRunID, DefaultGeneration, items); err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(generated.Bytes(), frozenRequests) || !bytes.Equal(generated.Bytes(), canonicalRequestFile(requests)) {
		t.Fatalf("frozen request bytes differ from provider JSONL")
	}
	if strings.Contains(generated.String(), `"ordinal"`) {
		t.Fatalf("provider JSONL contains validation-only ordinal: %s", generated.String())
	}
}

func TestFrozenFixtureRejectsModelPromptAndResponseDrift(t *testing.T) {
	fixture, _ := loadTestFixture(t)
	codec, err := enrichment.NewTranslationCodec(enrichment.LLMConfig{Model: fixture.Model})
	if err != nil {
		t.Fatal(err)
	}
	for name, mutate := range map[string]func(*Fixture){
		"model":  func(f *Fixture) { f.Model = "different-model" },
		"prompt": func(f *Fixture) { f.PromptVersion = "different-prompt" },
	} {
		t.Run(name, func(t *testing.T) {
			changed := fixture
			mutate(&changed)
			if _, _, err := FrozenRequests(codec, changed, DefaultRunID, DefaultGeneration); err == nil || !strings.Contains(err.Error(), "codec does not match frozen model or prompt version") {
				t.Fatalf("fixture drift was accepted: %v", err)
			}
		})
	}

	unknown := fixture
	unknown.Responses = append(append([]FixtureResponse(nil), fixture.Responses...), FixtureResponse{Ordinal: 99})
	if err := unknown.ValidateResponses(); err == nil || !strings.Contains(err.Error(), "not an accepted manifest item") {
		t.Fatalf("unknown response ordinal was accepted: %v", err)
	}
	missing := fixture
	missing.Responses = append([]FixtureResponse(nil), fixture.Responses[:len(fixture.Responses)-1]...)
	if err := missing.ValidateResponses(); err == nil || !strings.Contains(err.Error(), "does not match accepted item count") {
		t.Fatalf("missing response ordinal was accepted: %v", err)
	}
}

func TestWriteMarkdownReportSeparatesSyntheticEvidenceAndRealMeasurement(t *testing.T) {
	fixture, _ := loadTestFixture(t)
	var report bytes.Buffer
	if err := WriteMarkdownReport(&report, Report{FixtureName: fixture.Name, ManifestDigest: "fixture-digest", Provider: fixture.Provider, ProviderVersion: fixture.ProviderVersion, Model: fixture.Model, Prompt: fixture.PromptVersion}); err != nil {
		t.Fatal(err)
	}
	for _, phrase := range []string{"Synthetic replay (not cutover evidence)", "Real-provider measurement", "not run", "quality", "operational recovery", "ADR-0031", "code revert"} {
		if !strings.Contains(report.String(), phrase) {
			t.Fatalf("report missing %q", phrase)
		}
	}
}

func TestDefaultFixtureFilesAreCheckedIn(t *testing.T) {
	for _, name := range []string{"manifest.json", "requests.jsonl", "responses.json"} {
		if _, err := os.Stat(filepath.Join("testdata", name)); errors.Is(err, os.ErrNotExist) {
			t.Fatal(err)
		}
	}
}

func TestDeterministicStubScenariosCoverRecoveryBoundaries(t *testing.T) {
	fixture, _ := loadTestFixture(t)
	codec, err := enrichment.NewTranslationCodec(enrichment.LLMConfig{Model: fixture.Model})
	if err != nil {
		t.Fatal(err)
	}
	_, items, err := FrozenRequests(codec, fixture, DefaultRunID, DefaultGeneration)
	if err != nil {
		t.Fatal(err)
	}
	output, err := fixedBatchOutput(codec, fixture, items, DefaultRunID, DefaultGeneration)
	if err != nil {
		t.Fatal(err)
	}

	t.Run("success", func(t *testing.T) {
		outcomes, missing, err := codec.DecodeBatchResultsPartial(DefaultRunID, DefaultGeneration, items, bytes.NewReader(output), nil)
		if err != nil || len(outcomes) != len(items) || len(missing) != 0 {
			t.Fatalf("outcomes=%d missing=%v err=%v", len(outcomes), missing, err)
		}
	})
	t.Run("partial failure", func(t *testing.T) {
		id, _ := enrichment.BatchCustomID(DefaultRunID, items[0].Ordinal, DefaultGeneration)
		errorLine := []byte(`{"custom_id":"` + id + `","error":{"code":"rate_limit_exceeded"}}`)
		partialOutput, outputErr := fixedBatchOutput(codec, fixture, items[1:], DefaultRunID, DefaultGeneration)
		if outputErr != nil {
			t.Fatal(outputErr)
		}
		outcomes, missing, err := codec.DecodeBatchResultsPartial(DefaultRunID, DefaultGeneration, items[1:], bytes.NewReader(partialOutput), bytes.NewReader(append(errorLine, '\n')))
		if err == nil || outcomes != nil {
			t.Fatalf("partial failure was not rejected for mismatched item set: outcomes=%v missing=%v err=%v", outcomes, missing, err)
		}
		outcomes, missing, err = codec.DecodeBatchResultsPartial(DefaultRunID, DefaultGeneration, items, bytes.NewReader(partialOutput), bytes.NewReader(append(errorLine, '\n')))
		if err != nil || len(outcomes) != len(items) || len(missing) != 0 || outcomes[items[0].Ordinal].Successful() {
			t.Fatalf("partial outcomes=%v missing=%v err=%v", outcomes, missing, err)
		}
	})
	t.Run("expiry", func(t *testing.T) {
		id, _ := enrichment.BatchCustomID(DefaultRunID, items[0].Ordinal, DefaultGeneration)
		errorLine := []byte(`{"custom_id":"` + id + `","error":{"code":"batch_expired"}}`)
		outcomes, missing, err := codec.DecodeBatchResultsPartial(DefaultRunID, DefaultGeneration, items, nil, bytes.NewReader(append(errorLine, '\n')))
		if err != nil || len(outcomes) != 1 || len(missing) != len(items)-1 {
			t.Fatalf("expiry outcomes=%v missing=%v err=%v", outcomes, missing, err)
		}
	})
	t.Run("cancellation", func(t *testing.T) {
		if !isTerminalStubStatus(enrichment.BatchStatusCancelled) || isTerminalStubStatus(enrichment.BatchStatusInProgress) {
			t.Fatal("cancellation terminal policy changed")
		}
	})
	t.Run("restart", func(t *testing.T) {
		first, second, err := ReplayFixedResponses(context.Background(), codec, fixture, mustRequests(t), DefaultRunID, DefaultGeneration)
		if err != nil || first.Artifact != second.Artifact || !first.ArtifactStable || !second.ArtifactStable {
			t.Fatalf("restart replay=%+v/%+v err=%v", first, second, err)
		}
	})
	t.Run("ambiguous submission", func(t *testing.T) {
		// No provider identity is proof of creation. The only safe stub result is
		// a manual-recovery decision; automatic resubmission would risk billing
		// the same frozen requests twice.
		if submissionDecision(false, false) != "fail_closed_manual_recovery" || submissionDecision(true, false) != "resume_existing" {
			t.Fatal("ambiguous submission did not fail closed")
		}
	})
}

func mustRequests(t *testing.T) []byte {
	_, requests := loadTestFixture(t)
	return requests
}

func isTerminalStubStatus(status enrichment.BatchStatus) bool {
	return status == enrichment.BatchStatusCompleted || status == enrichment.BatchStatusFailed || status == enrichment.BatchStatusExpired || status == enrichment.BatchStatusCancelled
}

func submissionDecision(remoteFound, creationConfirmed bool) string {
	if remoteFound && !creationConfirmed {
		return "resume_existing"
	}
	if !remoteFound && !creationConfirmed {
		return "fail_closed_manual_recovery"
	}
	return "created"
}
