-- This correction is intentionally not reversed. It removes candidates that
-- an earlier migration fabricated from current analysis, and the original
-- active/inactive distinction cannot be recovered from the remaining rows.
