DROP VIEW public.my_books_evidence;
DROP TABLE public.book_covers;

CREATE VIEW public.my_books_evidence AS
 SELECT (b.id)::text AS book_id,
    (b.owner_id)::text AS book_owner_id,
    b.title AS book_title,
    b.metadata_provenance AS book_metadata_provenance,
    b.language_state AS book_language_state,
    COALESCE(b.language_tag, ''::text) AS book_language_tag,
    b.created_at AS book_created_at,
    b.updated_at AS book_updated_at,
    COALESCE(sme.source_id, ''::text) AS source_id,
    COALESCE(sme.source_owner_id, ''::text) AS source_owner_id,
    COALESCE(sme.source_language, ''::text) AS source_language,
    COALESCE(sme.source_identifier, ''::text) AS source_identifier,
    COALESCE(sme.source_title, ''::text) AS source_title,
    COALESCE(sme.source_media_type, ''::text) AS source_media_type,
    COALESCE(sme.content_hash, ''::text) AS source_content_hash,
    COALESCE(sme.content_digest, ''::text) AS source_content_digest,
    COALESCE(sme.content_revision_id, ''::text) AS source_content_revision_id,
    COALESCE(sme.content_snapshot_id, ''::text) AS source_content_snapshot_id,
    COALESCE(sme.digest_version, 0) AS source_digest_version,
    sme.source_created_at,
    (sme.source_id IS NOT NULL) AS acquired,
    COALESCE(sme.analysis_status, ''::text) AS analysis_status,
    COALESCE(sme.analysis_state, ''::text) AS analysis_state,
    COALESCE(sme.analysis_run_id, ''::text) AS analysis_run_id,
    COALESCE(sme.corpus_id, ''::text) AS corpus_id,
    COALESCE(sme.analysis_job_id, (0)::bigint) AS analysis_job_id,
    COALESCE(b.author, ''::text) AS book_author
   FROM ((public.books b
     JOIN public.book_membership m ON (((m.owner_id = b.owner_id) AND (m.book_id = b.id) AND (m.state = 'active'::text))))
     LEFT JOIN ( SELECT source_material_evidence.source_id,
            source_material_evidence.source_owner_id,
            source_material_evidence.source_language,
            source_material_evidence.source_identifier,
            source_material_evidence.source_title,
            source_material_evidence.source_media_type,
            source_material_evidence.book_id,
            source_material_evidence.book_title,
            source_material_evidence.content_hash,
            source_material_evidence.content_digest,
            source_material_evidence.content_revision_id,
            source_material_evidence.content_snapshot_id,
            source_material_evidence.digest_version,
            source_material_evidence.source_created_at,
            source_material_evidence.analysis_status,
            source_material_evidence.analysis_state,
            source_material_evidence.analysis_run_id,
            source_material_evidence.corpus_id,
            source_material_evidence.analysis_job_id,
            source_material_evidence.is_current_analysis,
            row_number() OVER (PARTITION BY source_material_evidence.source_owner_id, source_material_evidence.book_id ORDER BY source_material_evidence.is_current_analysis DESC, source_material_evidence.source_created_at DESC, source_material_evidence.source_id DESC) AS source_rn
           FROM public.source_material_evidence) sme ON (((sme.source_owner_id = (b.owner_id)::text) AND (sme.book_id = (b.id)::text) AND (sme.source_rn = 1))));
