package cardexport

import (
	"archive/zip"
	"bytes"
	"crypto/sha1"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	_ "modernc.org/sqlite"
)

// renderAPKG writes Anki's documented legacy schema version 11. Anki imports
// collection.anki2 from a ZIP package and upgrades it to the current schema.
// The package contains no media, so its media manifest is an empty JSON object.
func renderAPKG(deckName string, notes []Note) ([]byte, error) {
	f, err := os.CreateTemp("", "mouseion-*.anki2")
	if err != nil {
		return nil, err
	}
	path := f.Name()
	defer os.Remove(path)
	if err = f.Close(); err != nil {
		return nil, err
	}

	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}
	if err = writeCollection(db, deckName, notes); err != nil {
		db.Close()
		return nil, err
	}
	if err = db.Close(); err != nil {
		return nil, err
	}

	collection, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer collection.Close()
	var out bytes.Buffer
	zw := zip.NewWriter(&out)
	w, err := zw.CreateHeader(&zip.FileHeader{Name: "collection.anki2", Method: zip.Store})
	if err == nil {
		_, err = io.Copy(w, collection)
	}
	if err == nil {
		var media io.Writer
		media, err = zw.Create("media")
		if err == nil {
			_, err = io.WriteString(media, "{}")
		}
	}
	if closeErr := zw.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

func writeCollection(db *sql.DB, deckName string, notes []Note) error {
	const schema = `
CREATE TABLE col (id integer primary key, crt integer not null, mod integer not null, scm integer not null, ver integer not null, dty integer not null, usn integer not null, ls integer not null, conf text not null, models text not null, decks text not null, dconf text not null, tags text not null);
CREATE TABLE notes (id integer primary key, guid text not null, mid integer not null, mod integer not null, usn integer not null, tags text not null, flds text not null, sfld text not null, csum integer not null, flags integer not null, data text not null);
CREATE TABLE cards (id integer primary key, nid integer not null, did integer not null, ord integer not null, mod integer not null, usn integer not null, type integer not null, queue integer not null, due integer not null, ivl integer not null, factor integer not null, reps integer not null, lapses integer not null, left integer not null, odue integer not null, odid integer not null, flags integer not null, data text not null);
CREATE TABLE revlog (id integer primary key, cid integer not null, usn integer not null, ease integer not null, ivl integer not null, lastIvl integer not null, factor integer not null, time integer not null, type integer not null);
CREATE TABLE graves (usn integer not null, oid integer not null, type integer not null);
CREATE INDEX ix_notes_usn ON notes (usn);
CREATE INDEX ix_cards_usn ON cards (usn);
CREATE INDEX ix_cards_nid ON cards (nid);
CREATE INDEX ix_cards_sched ON cards (did, queue, due);
CREATE INDEX ix_revlog_usn ON revlog (usn);
CREATE INDEX ix_revlog_cid ON revlog (cid);`
	if _, err := db.Exec(schema); err != nil {
		return fmt.Errorf("create Anki schema: %w", err)
	}
	modelID, deckID := stableID("model|"+noteTypeName), stableID("deck|"+deckName)
	model := modelMetadata(modelID, deckID)
	deck := legacyDeck{
		Desc: "Generated by Mouseion", Name: deckName, ExtendRev: 0, USN: -1,
		Collapsed: false, BrowserCollapsed: false, NewToday: [2]int{0, 0},
		TimeToday: [2]int{0, 0}, Dyn: 0, ExtendNew: 0, Conf: 1,
		RevToday: [2]int{0, 0}, LrnToday: [2]int{0, 0}, ID: deckID, Mod: 0,
	}
	models, err := json.Marshal(map[string]any{strconv.FormatInt(modelID, 10): model})
	if err != nil {
		return fmt.Errorf("marshal Anki models: %w", err)
	}
	decks, err := json.Marshal(map[string]legacyDeck{strconv.FormatInt(deckID, 10): deck})
	if err != nil {
		return fmt.Errorf("marshal Anki decks: %w", err)
	}
	dconf, err := json.Marshal(map[string]legacyDeckConfig{"1": defaultDeckConfig()})
	if err != nil {
		return fmt.Errorf("marshal Anki deck configuration: %w", err)
	}
	if _, err := db.Exec(`INSERT INTO col VALUES(1,0,0,0,11,0,0,0,?,?,?,?,?)`, `{}`, string(models), string(decks), string(dconf), `{}`); err != nil {
		return fmt.Errorf("insert collection: %w", err)
	}
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	for i, note := range notes {
		nid, cid := stableID("note|"+note.Key), stableID("card|"+note.Key)
		fields := strings.Join(noteFields(note), "\x1f")
		tags := " " + strings.Join(note.Tags, " ") + " "
		if _, err = tx.Exec(`INSERT INTO notes VALUES(?,?,?,?,?,?,?,?,?,?,?)`, nid, note.Key[:20], modelID, 0, -1, tags, fields, note.Identity, fieldChecksum(note.Identity), 0, ""); err != nil {
			return fmt.Errorf("insert note: %w", err)
		}
		if _, err = tx.Exec(`INSERT INTO cards VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, cid, nid, deckID, 0, 0, -1, 0, 0, i+1, 0, 0, 0, 0, 0, 0, 0, 0, ""); err != nil {
			return fmt.Errorf("insert card: %w", err)
		}
	}
	return tx.Commit()
}

type legacyDeck struct {
	Desc             string `json:"desc"`
	Name             string `json:"name"`
	ExtendRev        int    `json:"extendRev"`
	USN              int    `json:"usn"`
	Collapsed        bool   `json:"collapsed"`
	BrowserCollapsed bool   `json:"browserCollapsed"`
	NewToday         [2]int `json:"newToday"`
	TimeToday        [2]int `json:"timeToday"`
	Dyn              int    `json:"dyn"`
	ExtendNew        int    `json:"extendNew"`
	Conf             int64  `json:"conf"`
	RevToday         [2]int `json:"revToday"`
	LrnToday         [2]int `json:"lrnToday"`
	ID               int64  `json:"id"`
	Mod              int64  `json:"mod"`
}

type legacyDeckConfig struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Mod      int64          `json:"mod"`
	USN      int            `json:"usn"`
	MaxTaken int            `json:"maxTaken"`
	Autoplay bool           `json:"autoplay"`
	Timer    int            `json:"timer"`
	ReplayQ  bool           `json:"replayq"`
	New      map[string]any `json:"new"`
	Rev      map[string]any `json:"rev"`
	Lapse    map[string]any `json:"lapse"`
	Dyn      bool           `json:"dyn"`
}

func defaultDeckConfig() legacyDeckConfig {
	return legacyDeckConfig{
		ID: 1, Name: "Default", Mod: 0, USN: 0, MaxTaken: 60, Autoplay: true, Timer: 0, ReplayQ: true,
		New:   map[string]any{"delays": []int{1, 10}, "ints": []int{1, 4}, "initialFactor": 2500, "order": 1, "perDay": 20, "bury": false},
		Rev:   map[string]any{"perDay": 200, "ivlFct": 1, "ease4": 1.3, "maxIvl": 36500, "hardFactor": 1.2, "bury": false},
		Lapse: map[string]any{"delays": []int{10}, "mult": 0, "minInt": 1, "leechFails": 8, "leechAction": 0},
		Dyn:   false,
	}
}

func modelMetadata(modelID, deckID int64) map[string]any {
	fields := make([]map[string]any, len(fieldNames))
	for i, name := range fieldNames {
		fields[i] = map[string]any{"name": name, "ord": i, "sticky": false, "rtl": false, "font": "Arial", "size": 20, "media": []any{}}
	}
	qfmt := `{{Text}}`
	afmt := `{{Text}}<hr id="answer"><div class="meta"><b>{{#Article}}{{Article}} {{/Article}}{{Lemma}}</b> · {{POS}}</div><div class="english">{{English}}</div><div class="sentence">{{EnglishSentence}}</div>`
	return map[string]any{"id": modelID, "name": noteTypeName, "type": 0, "mod": 0, "usn": -1, "sortf": 0, "did": deckID, "tmpls": []any{map[string]any{"name": "Recognition", "ord": 0, "qfmt": qfmt, "afmt": afmt, "bqfmt": "", "bafmt": "", "did": nil}}, "flds": fields, "css": `.card { font-family: Arial; font-size: 20px; text-align: left; color: #222; background: #fff; line-height: 1.45; } .meta { margin-top: 1em; } .sentence, .english { max-width: 42em; margin: .65em auto 0; text-align: left; }`, "latexPre": "", "latexPost": "", "req": []any{[]any{0, "all", []any{0}}}, "vers": []any{}, "tags": []any{}}
}

func stableID(value string) int64 {
	sum := sha1.Sum([]byte(value))
	// Collection metadata stores IDs in JSON as well as SQLite. Keep them below
	// 2^53 so every importer can represent them exactly before writing SQLite.
	n, _ := strconv.ParseInt(hex.EncodeToString(sum[:8])[:13], 16, 64)
	return n
}

func fieldChecksum(value string) int64 {
	sum := sha1.Sum([]byte(value))
	n, _ := strconv.ParseInt(hex.EncodeToString(sum[:])[:8], 16, 64)
	return n
}
