package cardexport

import (
	"archive/zip"
	"bytes"
	"crypto/sha1"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	_ "github.com/mattn/go-sqlite3"
)

// renderAPKG writes Anki's documented legacy schema version 11. Anki imports
// collection.anki2 from a ZIP package and upgrades it to the current schema.
// The package contains no media, so its media manifest is an empty JSON object.
func renderAPKG(deckName string, notes []Note) ([]byte, error) {
	f, err := os.CreateTemp("", "mouseion-*.anki2")
	if err != nil {
		return nil, err
	}
	path := f.Name()
	defer os.Remove(path)
	if err = f.Close(); err != nil {
		return nil, err
	}

	db, err := sql.Open("sqlite3", path)
	if err != nil {
		return nil, err
	}
	if err = writeCollection(db, deckName, notes); err != nil {
		db.Close()
		return nil, err
	}
	if err = db.Close(); err != nil {
		return nil, err
	}

	collection, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer collection.Close()
	var out bytes.Buffer
	zw := zip.NewWriter(&out)
	w, err := zw.CreateHeader(&zip.FileHeader{Name: "collection.anki2", Method: zip.Store})
	if err == nil {
		_, err = io.Copy(w, collection)
	}
	if err == nil {
		var media io.Writer
		media, err = zw.Create("media")
		if err == nil {
			_, err = io.WriteString(media, "{}")
		}
	}
	if closeErr := zw.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

func writeCollection(db *sql.DB, deckName string, notes []Note) error {
	const schema = `
CREATE TABLE col (id integer primary key, crt integer not null, mod integer not null, scm integer not null, ver integer not null, dty integer not null, usn integer not null, ls integer not null, conf text not null, models text not null, decks text not null, dconf text not null, tags text not null);
CREATE TABLE notes (id integer primary key, guid text not null, mid integer not null, mod integer not null, usn integer not null, tags text not null, flds text not null, sfld text not null, csum integer not null, flags integer not null, data text not null);
CREATE TABLE cards (id integer primary key, nid integer not null, did integer not null, ord integer not null, mod integer not null, usn integer not null, type integer not null, queue integer not null, due integer not null, ivl integer not null, factor integer not null, reps integer not null, lapses integer not null, left integer not null, odue integer not null, odid integer not null, flags integer not null, data text not null);
CREATE TABLE revlog (id integer primary key, cid integer not null, usn integer not null, ease integer not null, ivl integer not null, lastIvl integer not null, factor integer not null, time integer not null, type integer not null);
CREATE TABLE graves (usn integer not null, oid integer not null, type integer not null);
CREATE INDEX ix_notes_usn ON notes (usn);
CREATE INDEX ix_cards_usn ON cards (usn);
CREATE INDEX ix_cards_nid ON cards (nid);
CREATE INDEX ix_cards_sched ON cards (did, queue, due);
CREATE INDEX ix_revlog_usn ON revlog (usn);
CREATE INDEX ix_revlog_cid ON revlog (cid);`
	if _, err := db.Exec(schema); err != nil {
		return fmt.Errorf("create Anki schema: %w", err)
	}
	modelID, deckID := stableID("model|"+noteTypeName), stableID("deck|"+deckName)
	model := modelMetadata(modelID, deckID)
	deck := map[string]any{"id": deckID, "name": deckName, "desc": "Generated by Mouseion", "mod": 0, "usn": -1, "dyn": 0, "collapsed": false, "extendNew": 0, "extendRev": 0}
	models, _ := json.Marshal(map[string]any{strconv.FormatInt(modelID, 10): model})
	decks, _ := json.Marshal(map[string]any{strconv.FormatInt(deckID, 10): deck})
	dconf := `{"1":{"id":1,"name":"Default","mod":0,"usn":0,"maxTaken":60,"autoplay":true,"timer":0,"replayq":true,"new":{"delays":[1,10],"ints":[1,4],"initialFactor":2500,"order":1,"perDay":20,"bury":false},"rev":{"perDay":200,"ivlFct":1,"ease4":1.3,"maxIvl":36500,"hardFactor":1.2,"bury":false},"lapse":{"delays":[10],"mult":0,"minInt":1,"leechFails":8,"leechAction":0},"dyn":false}}`
	if _, err := db.Exec(`INSERT INTO col VALUES(1,0,0,0,11,0,0,0,?,?,?,?,?)`, `{}`, string(models), string(decks), dconf, `{}`); err != nil {
		return fmt.Errorf("insert collection: %w", err)
	}
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	for i, note := range notes {
		nid, cid := stableID("note|"+note.Key), stableID("card|"+note.Key)
		fields := strings.Join(noteFields(note), "\x1f")
		tags := " " + strings.Join(note.Tags, " ") + " "
		if _, err = tx.Exec(`INSERT INTO notes VALUES(?,?,?,?,?,?,?,?,?,?,?)`, nid, note.Key[:20], modelID, 0, -1, tags, fields, note.Text, fieldChecksum(note.Text), 0, ""); err != nil {
			return fmt.Errorf("insert note: %w", err)
		}
		if _, err = tx.Exec(`INSERT INTO cards VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, cid, nid, deckID, 0, 0, -1, 0, 0, i+1, 0, 0, 0, 0, 0, 0, 0, 0, ""); err != nil {
			return fmt.Errorf("insert card: %w", err)
		}
	}
	return tx.Commit()
}

func modelMetadata(modelID, deckID int64) map[string]any {
	fields := make([]map[string]any, len(fieldNames))
	for i, name := range fieldNames {
		fields[i] = map[string]any{"name": name, "ord": i, "sticky": false, "rtl": false, "font": "Arial", "size": 20, "media": []any{}}
	}
	qfmt := `{{cloze:Text}}`
	afmt := `{{cloze:Text}}<hr id="answer"><div class="meta"><b>{{Lemma}}</b> · {{Morph}} · {{POS}}</div><div class="english">{{English}}</div><div class="sentence">{{EnglishSentence}}</div>`
	return map[string]any{"id": modelID, "name": noteTypeName, "type": 1, "mod": 0, "usn": -1, "sortf": 0, "did": deckID, "tmpls": []any{map[string]any{"name": "Cloze", "ord": 0, "qfmt": qfmt, "afmt": afmt, "bqfmt": "", "bafmt": "", "did": nil}}, "flds": fields, "css": `.card { font-family: Arial; font-size: 20px; text-align: left; color: #222; background: #fff; line-height: 1.45; } .meta { margin-top: 1em; } .english, .sentence { margin-top: .65em; }`, "latexPre": "", "latexPost": "", "req": []any{[]any{0, "all", []any{0}}}, "vers": []any{}, "tags": []any{}}
}

func stableID(value string) int64 {
	sum := sha1.Sum([]byte(value))
	n, _ := strconv.ParseInt(hex.EncodeToString(sum[:8])[:15], 16, 64)
	return n
}

func fieldChecksum(value string) int64 {
	sum := sha1.Sum([]byte(value))
	n, _ := strconv.ParseInt(hex.EncodeToString(sum[:])[:8], 16, 64)
	return n
}
