package cardexport

import (
	"archive/zip"
	"bytes"
	"database/sql"
	"encoding/csv"
	"encoding/json"
	"io"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/justin-hayes/mouseion/internal/analyzer"
	"github.com/justin-hayes/mouseion/internal/dictionary"
	"github.com/justin-hayes/mouseion/internal/domain"
	"github.com/justin-hayes/mouseion/internal/enrichment"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestDownloadFilenameAndDeckName(t *testing.T) {
	assert.Equal(t, "Mouseion::de::Das archaische Griechenland", DeckName("de", "Das archaische Griechenland"))
	assert.Equal(t, "Über_.._Buch___.apkg", DownloadFilename(`  Über/../Buch:*?  `))
	a, b := DownloadFilename("../"), DownloadFilename("../")
	assert.Equal(t, b, a)
	assert.True(t, strings.HasPrefix(a, "mouseion-deck-"))
	assert.True(t, strings.HasSuffix(a, ".apkg"))
}

func TestDeckDescriptionRetainsDictionaryAttribution(t *testing.T) {
	assert.Equal(t, "Generated by Mouseion", deckDescription([]RenderInput{{Language: "de"}}))
	assert.Equal(t, "Generated by Mouseion\n\n"+dictionary.AttributionNotice, deckDescription([]RenderInput{{DictionaryProviderVersion: "dump=2026-09-14", CandidateSenses: []enrichment.LexicalSense{{EvidenceID: "wiktionary:1", Gloss: "house"}}}}))
}

func TestBoldTargetEscapesHTMLAndClozeSyntax(t *testing.T) {
	got, err := BoldTarget(`<b>Das {{falsche}} Haus & mehr.</b>`, "Haus")
	require.NoError(t, err)
	want := `&lt;b&gt;Das &#123;&#123;falsche&#125;&#125; <b>Haus</b> &amp; mehr.&lt;/b&gt;`
	assert.Equal(t, want, got)
}

func TestAnkiPackageContractAndStableIDs(t *testing.T) {
	note := Note{Key: DedupKey("de", "haus", "NOUN", "alice"), Identity: strings.Repeat("a", 64), Text: "Das <b>Haus</b> ist heute sehr ruhig.", Article: "das", Lemma: "Haus", Plural: "Häuser", IPA: "/haʊ̯s/", PrincipalParts: "geht · ging · gegangen", POS: "NOUN", Gloss: "home", English: "house", EnglishSentence: "The house is very quiet today.", BookTitle: "Das archaische Griechenland", Tags: []string{"Mouseion", "lang::de", "pos::NOUN", "source::Das_archaische_Griechenland"}}
	missingSentenceTranslation := note
	missingSentenceTranslation.Key = DedupKey("de", "baum", "NOUN", "alice")
	missingSentenceTranslation.Identity = strings.Repeat("b", 64)
	missingSentenceTranslation.Article = "der"
	missingSentenceTranslation.Lemma = "Baum"
	missingSentenceTranslation.English = "tree"
	missingSentenceTranslation.EnglishSentence = ""
	deckName := DeckName("de", note.BookTitle)
	notes := []Note{note, missingSentenceTranslation}
	a, err := renderAPKG(t.Context(), deckName, notes, dictionary.AttributionNotice)
	require.NoError(t, err)
	b, err := renderAPKG(t.Context(), deckName, notes, dictionary.AttributionNotice)
	require.NoError(t, err)
	assert.True(t, bytes.Equal(a, b), "package bytes are not deterministic")
	zr, err := zip.NewReader(bytes.NewReader(a), int64(len(a)))
	require.NoError(t, err)
	members := map[string]*zip.File{}
	for _, f := range zr.File {
		members[f.Name] = f
	}
	require.NotNil(t, members["collection.anki2"])
	require.NotNil(t, members["media"])
	assert.Len(t, members, 2)
	media, err := members["media"].Open()
	require.NoError(t, err)
	t.Cleanup(func() {
		if err := media.Close(); err != nil {
			t.Errorf("media cleanup failed: %v", err)
		}
	})
	var mediaMap map[string]string
	err = json.NewDecoder(media).Decode(&mediaMap)
	require.NoError(t, err)
	assert.Empty(t, mediaMap)
	dbReader, err := members["collection.anki2"].Open()
	require.NoError(t, err)
	t.Cleanup(func() {
		if err := dbReader.Close(); err != nil {
			t.Errorf("database ZIP member cleanup failed: %v", err)
		}
	})
	dbBytes, err := io.ReadAll(dbReader)
	require.NoError(t, err)
	dbPath := t.TempDir() + "/collection.anki2"
	err = os.WriteFile(dbPath, dbBytes, 0o600)
	require.NoError(t, err)
	db, err := sql.Open("sqlite", dbPath)
	require.NoError(t, err)
	t.Cleanup(func() {
		if err := db.Close(); err != nil {
			t.Errorf("SQLite database cleanup failed: %v", err)
		}
	})
	var modelsJSON, decksJSON, dconfJSON string
	err = db.QueryRowContext(t.Context(), `SELECT models,decks,dconf FROM col`).Scan(&modelsJSON, &decksJSON, &dconfJSON)
	require.NoError(t, err)
	assert.Contains(t, modelsJSON, `"name":"Mouseion Vocab Recognition"`)
	assert.Contains(t, modelsJSON, `"qfmt":"{{Text}}"`)
	assert.Contains(t, modelsJSON, `\u003cdiv class=\"gloss meaning-block\"\u003e{{Gloss}}\u003c/div\u003e`)
	assert.Contains(t, modelsJSON, `\u003cdiv class=\"sentence contextual-translation\"\u003e{{EnglishSentence}}\u003c/div\u003e`)
	assert.NotContains(t, modelsJSON, `\u003cdiv class=\"english\"\u003e{{English}}\u003c/div\u003e`)
	assert.NotContains(t, modelsJSON, `{{Morph}}`)
	assert.NotContains(t, modelsJSON, `{{SourceSentence}}`)
	assert.NotContains(t, strings.ToLower(modelsJSON), "cloze")
	assert.NotContains(t, modelsJSON, `"name":"Morph"`)
	assert.Contains(t, decksJSON, deckName)
	assert.Contains(t, decksJSON, dictionary.AttributionNotice)
	var models map[string]struct {
		Fields []struct {
			Name string `json:"name"`
		} `json:"flds"`
	}
	err = json.Unmarshal([]byte(modelsJSON), &models)
	require.NoError(t, err)
	gotNames := make([]string, 0, len(fieldNames))
	for _, model := range models {
		for _, field := range model.Fields {
			gotNames = append(gotNames, field.Name)
		}
	}
	assert.Equal(t, strings.Join(fieldNames, ","), strings.Join(gotNames, ","))
	assertLegacyCollectionContract(t, modelsJSON, decksJSON, dconfJSON, deckName)
	var noteID, cardCount, checksum int64
	var fields, tags, sortField string
	err = db.QueryRowContext(t.Context(), `SELECT id,flds,tags,sfld,csum FROM notes WHERE guid=?`, note.Key[:20]).Scan(&noteID, &fields, &tags, &sortField, &checksum)
	require.NoError(t, err)
	serializedFields := strings.Split(fields, "\x1f")
	assert.Equal(t, stableID("note|"+note.Key), noteID)
	require.Len(t, serializedFields, 12)
	assert.Equal(t, note.Identity, serializedFields[0])
	assert.Equal(t, note.Text, serializedFields[1])
	assert.Equal(t, note.Article, serializedFields[2])
	assert.Equal(t, note.Lemma, serializedFields[3])
	assert.Equal(t, note.Plural, serializedFields[4])
	assert.Equal(t, note.IPA, serializedFields[5])
	assert.Equal(t, note.PrincipalParts, serializedFields[6])
	assert.Equal(t, note.POS, serializedFields[7])
	assert.Equal(t, note.Gloss, serializedFields[8])
	assert.Equal(t, note.English, serializedFields[9])
	assert.Equal(t, note.EnglishSentence, serializedFields[10])
	assert.Equal(t, note.BookTitle, serializedFields[11])
	assert.Equal(t, note.Identity, sortField)
	assert.Equal(t, fieldChecksum(note.Identity), checksum)
	assert.Contains(t, tags, " Mouseion ")
	assert.NotContains(t, strings.ToLower(tags), "leech")
	err = db.QueryRowContext(t.Context(), `SELECT flds FROM notes WHERE guid=?`, missingSentenceTranslation.Key[:20]).Scan(&fields)
	require.NoError(t, err)
	serializedFields = strings.Split(fields, "\x1f")
	require.Len(t, serializedFields, 12)
	assert.Equal(t, "", serializedFields[10])
	var distinctSortFields int64
	err = db.QueryRowContext(t.Context(), `SELECT count(DISTINCT sfld) FROM notes`).Scan(&distinctSortFields)
	require.NoError(t, err)
	assert.Equal(t, int64(2), distinctSortFields)
	err = db.QueryRowContext(t.Context(), `SELECT count(*) FROM cards`).Scan(&cardCount)
	require.NoError(t, err)
	assert.Equal(t, int64(2), cardCount)
}

func TestAnkiCardPresentationHierarchy(t *testing.T) {
	note := Note{Key: strings.Repeat("a", 64), Identity: strings.Repeat("b", 64), Text: "Das <b>Haus</b> ist ruhig.", Lemma: "Haus", Plural: "Häuser", IPA: "/haʊ̯s/", PrincipalParts: "geht · ging · gegangen", POS: "NOUN", Gloss: "house", EnglishSentence: "The house is quiet."}
	apkg, err := renderAPKG(t.Context(), "Mouseion::de::Preview", []Note{note}, "")
	require.NoError(t, err)

	modelsJSON := collectionColumn(t, apkg, "models")
	var models map[string]struct {
		Templates []struct {
			Answer string `json:"afmt"`
		} `json:"tmpls"`
		CSS string `json:"css"`
	}
	require.NoError(t, json.Unmarshal([]byte(modelsJSON), &models))
	require.Len(t, models, 1)
	var model struct {
		Templates []struct {
			Answer string `json:"afmt"`
		} `json:"tmpls"`
		CSS string `json:"css"`
	}
	for _, candidate := range models {
		model = candidate
	}
	require.Len(t, model.Templates, 1)
	answer := model.Templates[0].Answer
	assert.Contains(t, answer, `<div class="card-back">`)
	assert.Contains(t, answer, `<div class="headword-line">`)
	assert.Contains(t, answer, `<strong class="headword">{{Lemma}}</strong>`)
	assert.Contains(t, answer, `<div class="gloss meaning-block">{{Gloss}}</div>`)
	assert.Contains(t, answer, `<div class="sentence contextual-translation">{{EnglishSentence}}</div>`)
	assert.NotContains(t, answer, `{{English}}`)
	assert.Less(t, strings.Index(answer, `class="headword-line"`), strings.Index(answer, `class="gloss meaning-block"`))
	assert.Less(t, strings.Index(answer, `class="gloss meaning-block"`), strings.Index(answer, `class="sentence contextual-translation"`))

	for _, token := range []string{
		"--mouseion-color-surface",
		"--mouseion-color-surface-raised",
		"--mouseion-color-text",
		"--mouseion-color-text-muted",
		"--mouseion-color-border",
		"--mouseion-font-reading",
		".headword",
		".inflection",
		".nightMode",
		"--mouseion-space-5",
		"--mouseion-width-reading",
	} {
		assert.Contains(t, model.CSS, token)
	}
	for _, token := range []string{
		"--mouseion-color-border: #b8c5cc",
		"--mouseion-color-accent-hover: #173f87",
		"--mouseion-color-text-muted: #aebdc5",
		"--mouseion-font-application: \"Avenir Next\", Avenir, \"Gill Sans\", \"Segoe UI\", sans-serif",
		"--mouseion-font-reading: \"Palatino Linotype\", Palatino, \"Book Antiqua\", Georgia, serif",
	} {
		assert.Contains(t, model.CSS, token)
	}
}

func TestGreekPreparedDeckUsesLanguageHierarchyAndTag(t *testing.T) {
	note, err := makeNote("alice", RenderInput{
		Language: "el", CanonicalLemma: "σπίτι", UPOS: "NOUN", Sentence: "Στο σπίτι ο Νίκος διαβάζει.",
		TargetWord: "σπίτι", SourceDocument: "Το σπίτι", Morphology: `{"Gender":"Neut","Number":"Sing"}`,
	})
	require.NoError(t, err)
	assert.Equal(t, []string{"Mouseion", "lang::el", "pos::NOUN", "source::Το_σπίτι"}, note.Tags)
	deckName := DeckName("el", "Το σπίτι")
	apkg, err := renderAPKG(t.Context(), deckName, []Note{note}, "")
	require.NoError(t, err)
	assert.Contains(t, collectionColumn(t, apkg, "decks"), deckName)
}

func TestCardPresentationPreviewIsFrozen(t *testing.T) {
	preview, err := os.ReadFile("testdata/recognition_card_preview.html")
	require.NoError(t, err)
	previewHTML := string(preview)
	assert.Contains(t, previewHTML, `href="../templates/recognition_card.css"`)
	assert.Contains(t, previewHTML, `content="../templates/recognition_card_back.html"`)
	assert.Contains(t, previewHTML, `class="card-back"`)
	assert.Contains(t, previewHTML, `class="card nightMode"`)
	assert.Contains(t, previewHTML, `class="gloss meaning-block"`)
	assert.NotContains(t, previewHTML, `class="english"`)
}

func collectionColumn(t *testing.T, apkg []byte, column string) string {
	t.Helper()
	zr, err := zip.NewReader(bytes.NewReader(apkg), int64(len(apkg)))
	require.NoError(t, err)
	for _, member := range zr.File {
		if member.Name != "collection.anki2" {
			continue
		}
		reader, openErr := member.Open()
		require.NoError(t, openErr)
		dbBytes, readErr := io.ReadAll(reader)
		require.NoError(t, readErr)
		require.NoError(t, reader.Close())
		dbPath := t.TempDir() + "/collection.anki2"
		require.NoError(t, os.WriteFile(dbPath, dbBytes, 0o600))
		db, openErr := sql.Open("sqlite", dbPath)
		require.NoError(t, openErr)
		t.Cleanup(func() {
			if err := db.Close(); err != nil {
				t.Errorf("SQLite database cleanup failed: %v", err)
			}
		})
		var value string
		require.NoError(t, db.QueryRowContext(t.Context(), "SELECT "+column+" FROM col").Scan(&value))
		return value
	}
	t.Fatalf("missing collection.anki2")
	return ""
}

func assertLegacyCollectionContract(t *testing.T, modelsJSON, decksJSON, dconfJSON, deckName string) {
	t.Helper()
	fixture, err := os.ReadFile("testdata/legacy_collection_contract.json")
	require.NoError(t, err)
	var contract map[string]map[string]string
	err = json.Unmarshal(fixture, &contract)
	require.NoError(t, err)

	collections := map[string]string{"models": modelsJSON, "decks": decksJSON, "dconf": dconfJSON}
	for collectionName, encoded := range collections {
		decoder := json.NewDecoder(strings.NewReader(encoded))
		decoder.UseNumber()
		var entries map[string]map[string]any
		err = decoder.Decode(&entries)
		require.NoError(t, err, "decode %s JSON: %v\n%s", collectionName, err, encoded)
		assert.Len(t, entries, 1)
		for key, entry := range entries {
			assertJSONShape(t, collectionName, entry, contract[collectionName])
			if id, ok := entry["id"].(json.Number); ok {
				value, numberErr := id.Int64()
				require.NoError(t, numberErr, "%s id %q is not JSON-safe: %v", collectionName, id, numberErr)
				assert.LessOrEqual(t, value, int64(1<<53-1), "%s id %q is not JSON-safe", collectionName, id)
				if collectionName != "dconf" {
					assert.Equal(t, id.String(), key, "%s key %q does not match id %q", collectionName, key, id)
				}
			}
			if collectionName == "decks" {
				assert.Equal(t, deckName, entry["name"], "deck name")
			}
		}
	}
}

func assertJSONShape(t *testing.T, name string, value map[string]any, shape map[string]string) {
	t.Helper()
	for field, wantType := range shape {
		got, ok := value[field]
		if !ok {
			assert.Fail(t, "%s missing required field %q", name, field)
			continue
		}
		valid := false
		switch wantType {
		case "string":
			_, valid = got.(string)
		case "number":
			_, valid = got.(json.Number)
		case "boolean":
			_, valid = got.(bool)
		case "object":
			_, valid = got.(map[string]any)
		case "array":
			_, valid = got.([]any)
		case "number_pair":
			pair, isArray := got.([]any)
			valid = isArray && len(pair) == 2
			for _, item := range pair {
				_, isNumber := item.(json.Number)
				valid = valid && isNumber
			}
		}
		if !valid {
			assert.Fail(t, "%s field %q = %#v, want %s", name, field, got, wantType)
		}
	}
}

func TestDedupKeyStableAndOwnerScoped(t *testing.T) {
	a := DedupKey("de", "Haus", "NOUN", "alice")
	assert.Len(t, a, 64)
	for _, b := range []string{DedupKey("de", "Haus", "NOUN", "bob"), DedupKey("fr", "Haus", "NOUN", "alice"), DedupKey("de", "haus", "NOUN", "alice"), DedupKey("de", "Haus", "VERB", "alice")} {
		assert.NotEqual(t, b, a, "distinct identity produced same key")
	}
}

func TestCardIdentityIsDeterministicCardSpecificAndOwnerScoped(t *testing.T) {
	entry := Entry{Language: "de", CanonicalLemma: "gut", UPOS: "ADJ", TargetWord: "die Besten›", Sentence: "Heute sah sie ‹die Besten› und lächelte freundlich.", SourceDocument: "Book", FirstEncounter: 42}
	identity := CardIdentity("alice", renderInputFromEntry(entry))
	cleanEntry := entry
	cleanEntry.TargetWord = "die Besten"
	assert.Len(t, identity, 64)
	assert.Equal(t, identity, CardIdentity("alice", renderInputFromEntry(entry)), "identity is unstable across equivalent legacy target forms")
	assert.Equal(t, identity, CardIdentity("alice", renderInputFromEntry(cleanEntry)), "identity is unstable across equivalent legacy target forms")
	variants := []struct {
		owner string
		entry Entry
	}{
		{owner: "bob", entry: entry},
		{owner: "alice", entry: func() Entry {
			value := entry
			value.CanonicalLemma = "die"
			value.UPOS = "DET"
			value.TargetWord = "‹die"
			return value
		}()},
		{owner: "alice", entry: func() Entry { value := entry; value.FirstEncounter++; return value }()},
	}
	for _, variant := range variants {
		assert.NotEqual(t, identity, CardIdentity(variant.owner, renderInputFromEntry(variant.entry)), "distinct card inputs collided: %+v", variant)
	}
}

func TestHighlightEnglishTargetSupportsSafeUniqueMultiwordMatches(t *testing.T) {
	tests := []struct{ name, translation, target, want string }{
		{"single", "The house is large.", "house", "The <b>house</b> is large."},
		{"multiword", "She visited the old house yesterday.", "old house", "She visited the <b>old house</b> yesterday."},
		{"missing", "The building is large.", "house", "The building is large."},
		{"ambiguous", "The house is beside another house.", "house", "The house is beside another house."},
		{"boundary", "The houses are large.", "house", "The houses are large."},
		{"markup", "The <script>alert(1)</script> house.", "house", "The &lt;script&gt;alert(1)&lt;/script&gt; <b>house</b>."},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			assert.Equal(t, test.want, HighlightEnglishTarget(test.translation, test.target))
		})
	}
}

func TestBoldTargetUsesOriginalUnicodeByteOffsets(t *testing.T) {
	for _, test := range []struct {
		sentence, target, want string
	}{
		{sentence: "ẞ Haus ist heute sehr groß.", target: "Haus", want: "ẞ <b>Haus</b> ist heute sehr groß."},
		{sentence: "Das ẞ steht heute dort ruhig.", target: "ß", want: "Das <b>ẞ</b> steht heute dort ruhig."},
		{sentence: "K Haus ist heute sehr groß.", target: "Haus", want: "K <b>Haus</b> ist heute sehr groß."},
		{sentence: "Heute blieb die Souveränität› vollständig erhalten.", target: "Souveränität›", want: "Heute blieb die <b>Souveränität</b>› vollständig erhalten."},
		{sentence: "Heute sah sie ‹die Besten› dort.", target: "die Besten›", want: "Heute sah sie ‹<b>die Besten</b>› dort."},
		{sentence: "Heute sah sie ‹die Besten› dort.", target: "‹die", want: "Heute sah sie ‹<b>die</b> Besten› dort."},
		{sentence: "Oggi O'Neill-like arriva insieme agli amici.", target: "O'Neill-like", want: "Oggi <b>O&#39;Neill-like</b> arriva insieme agli amici."},
	} {
		got, err := BoldTarget(test.sentence, test.target)
		require.NoError(t, err)
		assert.Equal(t, test.want, got)
	}
}

func TestAnkiCardSchemaRegressionContract(t *testing.T) {
	assert.Equal(t, []string{"Identity", "Text", "Article", "Lemma", "Plural", "IPA", "PrincipalParts", "POS", "Gloss", "English", "EnglishSentence", "BookTitle"}, fieldNames)
	model := modelMetadata(1, 2)
	modelFields, ok := model["flds"].([]map[string]any)
	require.True(t, ok)
	modelNames := make([]string, len(modelFields))
	for i, field := range modelFields {
		modelNames[i], ok = field["name"].(string)
		require.True(t, ok)
	}
	assert.Equal(t, fieldNames, modelNames)
	assert.False(t, containsString(modelNames, "Morph"))
	assert.False(t, containsString(modelNames, "SourceSentence"))
	templates, ok := model["tmpls"].([]any)
	require.True(t, ok)
	templateMap, ok := templates[0].(map[string]any)
	require.True(t, ok)
	template, ok := templateMap["afmt"].(string)
	require.True(t, ok)
	assert.Contains(t, template, `{{#Article}}<span class="article">{{Article}}</span><span class="article-space" data-article="{{Article}}"> </span>{{/Article}}<strong class="headword">{{Lemma}}</strong>`)
	assert.Contains(t, template, `{{#Plural}} <span class="inflection plural">(Pl. {{Plural}})</span>{{/Plural}}`)
	assert.Contains(t, template, `{{#IPA}} <span class="inflection pronunciation">{{IPA}}</span>{{/IPA}}`)
	assert.Contains(t, template, `{{#PrincipalParts}} <span class="inflection principal-parts">{{PrincipalParts}}</span>{{/PrincipalParts}}`)
	assert.Contains(t, template, `<div class="gloss meaning-block">{{Gloss}}</div>`)
	assert.Contains(t, template, `<div class="sentence contextual-translation">{{EnglishSentence}}</div>`)
	assert.NotContains(t, template, `<div class="english">{{English}}</div>`)
	css, ok := model["css"].(string)
	require.True(t, ok)
	assert.Contains(t, css, `.article-space[data-article="l'"]`)
	assert.Contains(t, css, `.inflection`)
	assert.Contains(t, css, `--mouseion-color-text-muted`)
	assert.NotContains(t, css, ".english")
	assert.NotContains(t, template, "{{Morph}}")
	assert.NotContains(t, template, "{{SourceSentence}}")

	german, err := makeNote("alice", renderInputFromEntry(Entry{Language: "de", CanonicalLemma: "haus", UPOS: "NOUN", Sentence: "Dieses Haus steht heute neben dem Bahnhof.", TargetWord: "Haus", Morphology: `{"Gender":"Neut"}`}))
	require.NoError(t, err)
	assert.Equal(t, "das", german.Article)
	assert.True(t, strings.HasPrefix(german.BackExtra, "das Haus\n"), "German noun article = %q, back = %q", german.Article, german.BackExtra)
	italian, err := makeNote("alice", renderInputFromEntry(Entry{Language: "it", CanonicalLemma: "portare", UPOS: "VERB", Sentence: "Domani Lucia porterà il pane fresco alla famiglia.", TargetWord: "porterà", Morphology: `{"Mood":"Ind"}`}))
	require.NoError(t, err)
	assert.Equal(t, "", italian.Article)

	path := t.TempDir() + "/collection.anki2"
	db, err := sql.Open("sqlite", path)
	require.NoError(t, err)
	t.Cleanup(func() {
		if err := db.Close(); err != nil {
			t.Errorf("SQLite database cleanup failed: %v", err)
		}
	})
	first := german
	first.Key = strings.Repeat("a", 64)
	first.Identity = "identity-a"
	second := german
	second.Key = strings.Repeat("b", 64)
	second.Identity = "identity-b"
	second.Article = "der"
	err = writeCollection(t.Context(), db, "deck", []Note{first, second}, "Generated by Mouseion")
	require.NoError(t, err)
	rows, err := db.QueryContext(t.Context(), `SELECT flds,sfld,csum FROM notes`)
	require.NoError(t, err)
	t.Cleanup(func() {
		if err := rows.Close(); err != nil {
			t.Errorf("SQLite rows cleanup failed: %v", err)
		}
	})
	seen := make(map[string]bool, 2)
	for rows.Next() {
		var fields, sortField string
		var checksum int64
		err := rows.Scan(&fields, &sortField, &checksum)
		require.NoError(t, err)
		serialized := strings.Split(fields, "\x1f")
		require.Len(t, serialized, 12)
		assert.Equal(t, sortField, serialized[0])
		assert.Equal(t, fieldChecksum(sortField), checksum)
		assert.True(t, sortField == first.Identity || sortField == second.Identity, "fields=%q sfld=%q csum=%d", fields, sortField, checksum)
		seen[sortField] = true
	}
	require.NoError(t, rows.Err())
	assert.Len(t, seen, 2, "distinct identity sort fields = %v", seen)
}

func TestMakeNoteRetainsEnglishFieldButOmitsItFromPersistedBack(t *testing.T) {
	note, err := makeNote("alice", renderInputFromEntry(Entry{
		Language: "de", CanonicalLemma: "haus", UPOS: "NOUN",
		Sentence: "Dieses Haus steht heute neben dem Bahnhof.", TargetWord: "Haus",
		Gloss: "dwelling", Translation: "lemma translation",
		SentenceTranslation: "This house stands beside the station.",
	}))
	require.NoError(t, err)
	assert.Equal(t, "lemma translation", note.English)
	assert.Equal(t, "Haus\nNOUN\ndwelling\nThis house stands beside the station.", note.BackExtra)
}

// TestAnkiNewCardOrderFollowsTextPosition pins the deck configuration so new
// cards are introduced in the order they appear in the source text. The export
// writes notes sorted by first encounter and binds each card's Anki position
// (due) to that index; the deck config must use ordered new-card presentation
// (order: 0 = "in order added") rather than randomizing (order: 1), or the
// text-order position encoded in due is discarded at review time.
func TestAnkiNewCardOrderFollowsTextPosition(t *testing.T) {
	notes := []Note{
		{Key: DedupKey("de", "wort", "NOUN", "alice"), Identity: "i1", Text: "Erstes <b>Wort</b>.", Article: "das", Lemma: "Wort", POS: "NOUN", English: "word", EnglishSentence: "First word.", BookTitle: "Buch"},
		{Key: DedupKey("de", "haus", "NOUN", "alice"), Identity: "i2", Text: "Zweites <b>Haus</b>.", Article: "das", Lemma: "Haus", POS: "NOUN", English: "house", EnglishSentence: "Second house.", BookTitle: "Buch"},
		{Key: DedupKey("de", "buch", "NOUN", "alice"), Identity: "i3", Text: "Drittes <b>Buch</b>.", Article: "das", Lemma: "Buch", POS: "NOUN", English: "book", EnglishSentence: "Third book.", BookTitle: "Buch"},
	}
	a, err := renderAPKG(t.Context(), DeckName("de", "Buch"), notes, "Generated by Mouseion")
	require.NoError(t, err)
	zr, err := zip.NewReader(bytes.NewReader(a), int64(len(a)))
	require.NoError(t, err)
	var db *sql.DB
	for _, f := range zr.File {
		if f.Name != "collection.anki2" {
			continue
		}
		rc, err := f.Open()
		require.NoError(t, err)
		t.Cleanup(func() {
			if err := rc.Close(); err != nil {
				t.Errorf("database ZIP member cleanup failed: %v", err)
			}
		})
		dbBytes, err := io.ReadAll(rc)
		require.NoError(t, err)
		require.NoError(t, rc.Close())
		path := t.TempDir() + "/collection.anki2"
		err = os.WriteFile(path, dbBytes, 0o600)
		require.NoError(t, err)
		db, err = sql.Open("sqlite", path)
		require.NoError(t, err)
		break
	}
	require.NotNil(t, db)
	t.Cleanup(func() {
		if err := db.Close(); err != nil {
			t.Errorf("SQLite database cleanup failed: %v", err)
		}
	})
	var dconfJSON string
	err = db.QueryRowContext(t.Context(), `SELECT dconf FROM col`).Scan(&dconfJSON)
	require.NoError(t, err)
	// dconf serializes a single keyed deck config named "1".
	var configs map[string]struct {
		New struct {
			Order float64 `json:"order"`
		} `json:"new"`
	}
	err = json.Unmarshal([]byte(dconfJSON), &configs)
	require.NoError(t, err)
	var order float64
	for _, cfg := range configs {
		order = cfg.New.Order
	}
	assert.Equal(t, float64(0), order, "new.card order = %v, want 0 (in order added), so text-position due is honored", order)
	// Every card's position must ascend 1..N, bound to text order.
	rows, err := db.QueryContext(t.Context(), `SELECT due FROM cards ORDER BY due`)
	require.NoError(t, err)
	t.Cleanup(func() {
		if err := rows.Close(); err != nil {
			t.Errorf("SQLite rows cleanup failed: %v", err)
		}
	})
	var dues []int64
	for rows.Next() {
		var due int64
		err = rows.Scan(&due)
		require.NoError(t, err)
		dues = append(dues, due)
	}
	require.NoError(t, rows.Err())
	assert.Len(t, dues, len(notes), "card due positions = %v, want len %d", dues, len(notes))
	for i, due := range dues {
		assert.Equal(t, int64(i+1), due, "card due positions = %v, want 1..%d in text order", dues, len(notes))
	}
}

func containsString(values []string, want string) bool {
	return slices.Contains(values, want)
}

func TestRenderTSVEscapesAndOrdersFields(t *testing.T) {
	n := Note{Key: "key", Identity: "identity", Text: "Grüße <b>Welt</b>", Article: "die", Lemma: "Welt", IPA: "/vɛlt/", PrincipalParts: "geht · ging · gegangen", POS: "NOUN", English: "world", EnglishSentence: "Hello world.", BookTitle: "My Book", Tags: []string{"Mouseion", "lang::de", "source::My_Book"}}
	got, err := RenderTSV([]Note{n}, "")
	require.NoError(t, err)
	r := csv.NewReader(strings.NewReader(got))
	r.Comma = '\t'
	rows, err := r.ReadAll()
	require.NoError(t, err)
	require.Len(t, rows, 1)
	require.Len(t, rows[0], 13)
	assert.Equal(t, strings.Join(noteFields(n), "\x1f"), strings.Join(rows[0][:12], "\x1f"))
	assert.Equal(t, "Mouseion lang::de source::My_Book", rows[0][12])
}

func TestRenderTSVIncludesDictionaryAttributionAsComment(t *testing.T) {
	got, err := RenderTSV([]Note{{Identity: "identity"}}, dictionary.AttributionNotice)
	require.NoError(t, err)
	assert.Contains(t, got, "# "+dictionary.AttributionNotice+"\n")

	r := csv.NewReader(strings.NewReader(got))
	r.Comma = '\t'
	r.Comment = '#'
	rows, err := r.ReadAll()
	require.NoError(t, err)
	assert.Equal(t, [][]string{{"identity", "", "", "", "", "", "", "", "", "", "", "", ""}}, rows)
}

func TestEscapeFieldCannotInjectAnkiFieldSeparator(t *testing.T) {
	got := escapeField("safe\x1finjected")
	assert.NotContains(t, got, "\x1f")
	assert.Equal(t, "safe&#31;injected", got)
}

func TestMakeNoteFormatsLemmaWithoutChangingTargetOrIdentity(t *testing.T) {
	entry := Entry{
		Language: "de", CanonicalLemma: "haus", UPOS: "NOUN",
		Sentence: "Die Häuser sind alt.", TargetWord: "Häuser", Morphology: `{"Gender":"Neut","Number":"Plur"}`,
	}
	note, err := makeNote("alice", renderInputFromEntry(entry))
	require.NoError(t, err)
	assert.Contains(t, note.Text, "<b>Häuser</b>")
	assert.Equal(t, "das", note.Article)
	assert.Equal(t, "Haus", note.Lemma)
	assert.True(t, strings.HasPrefix(note.BackExtra, "das Haus\n"))
	assert.Equal(t, DedupKey("de", "haus", "NOUN", "alice"), note.Key, "note key = %q, want canonical identity key %q", note.Key, DedupKey("de", "haus", "NOUN", "alice"))
}

func TestMakeNoteDerivesNounArticleFromMorphology(t *testing.T) {
	for _, test := range []struct {
		name, language, lemma, sentence, target, morphology, wantArticle, wantLemma string
	}{
		{name: "feminine ignores declined context", language: "de", sentence: "Bei der Iteration wurde das Ergebnis erneut geprüft.", target: "Iteration", morphology: `{"Case":"Dat","Gender":"Fem","Number":"Sing"}`, wantArticle: "die", wantLemma: "Iteration"},
		{name: "neuter without context article", language: "de", sentence: "Dieses Ruderblatt wurde gestern sorgfältig ausgetauscht.", target: "Ruderblatt", morphology: `{"Gender":"Neut","Number":"Sing"}`, wantArticle: "das", wantLemma: "Ruderblatt"},
		{name: "masculine singular", language: "de", sentence: "Dort steht ein Baum seit vielen Jahren.", target: "Baum", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "der", wantLemma: "Baum"},
		{name: "plural inflection uses lemma gender", language: "de", lemma: "haus", sentence: "Viele Häuser stehen seit Jahren am See.", target: "Häuser", morphology: `{"Gender":"Neut","Number":"Plur"}`, wantArticle: "das", wantLemma: "Haus"},
		{name: "plural only without gender", language: "de", lemma: "eltern", sentence: "Meine Eltern wohnen seit Jahren am See.", target: "Eltern", morphology: `{"Number":"Plur"}`, wantArticle: "die", wantLemma: "Eltern"},
		{name: "gender sufficient when number missing", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `{"Gender":"Neut"}`, wantArticle: "das", wantLemma: "Haus"},
		{name: "missing gender and singular number", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `{"Number":"Sing"}`, wantLemma: "Haus"},
		{name: "consistent gender across number variants", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `[{"Gender":"Neut","Number":"Sing"},{"Gender":"Neut","Number":"Plur"}]`, wantArticle: "das", wantLemma: "Haus"},
		{name: "ambiguous gender variants", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `[{"Gender":"Neut","Number":"Sing"},{"Gender":"Masc","Number":"Sing"}]`, wantLemma: "Haus"},
		{name: "malformed morphology", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `{`, wantLemma: "Haus"},
		{name: "German plural article form falls back to masculine gender", language: "de", sentence: "Viele Gauner wurden verhaftet.", target: "Gauner", morphology: `{"Article":"Gauner","Gender":"Masc","Number":"Plur"}`, wantArticle: "der", wantLemma: "Gauner"},
		{name: "German plural article form falls back to feminine gender", language: "de", sentence: "Feigheiten werden nicht belohnt.", target: "Feigheiten", morphology: `{"Article":"Feigheiten","Gender":"Fem","Number":"Plur"}`, wantArticle: "die", wantLemma: "Feigheiten"},
		{name: "German accusative article falls back to masculine gender", language: "de", sentence: "Ich sehe den Gauner.", target: "Gauner", morphology: `{"Article":"den","Gender":"Masc","Number":"Sing"}`, wantArticle: "der", wantLemma: "Gauner"},
		{name: "German dative article falls back to masculine gender", language: "de", sentence: "Ich helfe dem Gauner.", target: "Gauner", morphology: `{"Article":"dem","Gender":"Masc","Number":"Sing"}`, wantArticle: "der", wantLemma: "Gauner"},
		{name: "German genitive article falls back to neuter gender", language: "de", sentence: "Die Farbe des Hauses ist schön.", target: "Hauses", morphology: `{"Article":"des","Gender":"Neut","Number":"Sing"}`, wantArticle: "das", wantLemma: "Hauses"},
		{name: "Italian plural article falls back to masculine gender", language: "it", sentence: "I libri sono sul tavolo.", target: "libri", morphology: `{"Article":"dei","Gender":"Masc","Number":"Plur"}`, wantArticle: "il", wantLemma: "libri"},
		{name: "Italian prepositional article falls back to masculine gender", language: "it", sentence: "Parlo del libro.", target: "libro", morphology: `{"Article":"del","Gender":"Masc","Number":"Sing"}`, wantArticle: "il", wantLemma: "libro"},
		{name: "Italian prepositional article falls back to feminine gender", language: "it", sentence: "Parlo della casa.", target: "casa", morphology: `{"Article":"della","Gender":"Fem","Number":"Sing"}`, wantArticle: "la", wantLemma: "casa"},
		{name: "Italian feminine", language: "it", sentence: "La casa è ancora molto grande oggi.", target: "casa", morphology: `{"Gender":"Fem","Number":"Sing"}`, wantArticle: "la", wantLemma: "casa"},
		{name: "Italian masculine", language: "it", sentence: "Il pane è ancora fresco oggi.", target: "pane", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "il", wantLemma: "pane"},
		{name: "Italian impure s masculine", language: "it", sentence: "Lo studente legge ancora oggi.", target: "studente", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "lo", wantLemma: "studente"},
		{name: "Italian z masculine", language: "it", sentence: "Lo zaino è ancora pieno oggi.", target: "zaino", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "lo", wantLemma: "zaino"},
		{name: "Italian masculine vowel", language: "it", sentence: "Uomo, vieni ancora qui oggi.", target: "uomo", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "l&#39;", wantLemma: "uomo"},
		{name: "Italian feminine vowel", language: "it", sentence: "Amica, vieni ancora qui oggi.", target: "amica", morphology: `{"Gender":"Fem","Number":"Sing"}`, wantArticle: "l&#39;", wantLemma: "amica"},
		{name: "Italian language tag with region", language: "it-IT", sentence: "La casa è ancora molto grande oggi.", target: "casa", morphology: `{"Gender":"Fem","Number":"Sing"}`, wantArticle: "la", wantLemma: "casa"},
		{name: "Greek masculine", language: "el", sentence: "Ο άνθρωπος διαβάζει σήμερα.", target: "άνθρωπος", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "ο", wantLemma: "άνθρωπος"},
		{name: "Greek feminine", language: "el", sentence: "Η πόλη είναι μεγάλη.", target: "πόλη", morphology: `{"Gender":"Fem","Number":"Sing"}`, wantArticle: "η", wantLemma: "πόλη"},
		{name: "Greek neuter", language: "el", sentence: "Το σπίτι είναι παλιό.", target: "σπίτι", morphology: `{"Gender":"Neut","Number":"Sing"}`, wantArticle: "το", wantLemma: "σπίτι"},
		{name: "Greek valid dictionary article wins", language: "el", sentence: "Ο δρόμος είναι μακρύς.", target: "δρόμος", morphology: `{"Gender":"Fem","Article":"ο","Number":"Sing"}`, wantArticle: "ο", wantLemma: "δρόμος"},
		{name: "Greek invalid gender", language: "el", sentence: "Το σπίτι είναι παλιό.", target: "σπίτι", morphology: `{"Gender":"Common","Number":"Sing"}`, wantLemma: "σπίτι"},
		{name: "Greek ambiguous gender variants", language: "el", sentence: "Το σπίτι είναι παλιό.", target: "σπίτι", morphology: `[{"Gender":"Neut","Number":"Sing"},{"Gender":"Masc","Number":"Sing"}]`, wantLemma: "σπίτι"},
	} {
		t.Run(test.name, func(t *testing.T) {
			lemma := test.lemma
			if lemma == "" {
				lemma = strings.ToLower(test.target)
			}
			note, err := makeNote("alice", renderInputFromEntry(Entry{Language: test.language, CanonicalLemma: lemma, UPOS: "NOUN", Sentence: test.sentence, TargetWord: test.target, Morphology: test.morphology}))
			require.NoError(t, err)
			assert.Equal(t, test.wantArticle, note.Article)
			assert.Equal(t, test.wantLemma, note.Lemma)
		})
	}
}

func TestMakeNoteDoesNotAddGreekArticleToNonNoun(t *testing.T) {
	note, err := makeNote("alice", renderInputFromEntry(Entry{
		Language: "el", CanonicalLemma: "είμαι", UPOS: "VERB", Sentence: "Είμαι εδώ.", TargetWord: "Είμαι",
		Morphology: `{"Gender":"Masc","Number":"Sing"}`,
	}))
	require.NoError(t, err)
	assert.Empty(t, note.Article)
}

func TestMakeNoteJoinsItalianElidedArticleWithoutSpace(t *testing.T) {
	note, err := makeNote("alice", renderInputFromEntry(Entry{
		Language: "it", CanonicalLemma: "uomo", UPOS: "NOUN",
		Sentence: "Uomo, vieni ancora qui oggi.", TargetWord: "uomo", Morphology: `{"Gender":"Masc","Number":"Sing"}`,
	}))
	require.NoError(t, err)
	assert.Equal(t, "l&#39;", note.Article)
	assert.True(t, strings.HasPrefix(note.BackExtra, "l&#39;uomo\n"))
}

func TestBestSentenceEvidencePreservesCompleteSourceText(t *testing.T) {
	const source = "  Vor dem alten Haus spielen heute mehrere fröhliche Kinder.  "
	candidate := domain.SelectionCandidate{
		CorpusID:           "corpus-1",
		CanonicalLemma:     "haus",
		ObservedForms:      []byte(`["Haus"]`),
		SentenceReferences: []byte(`[{"text":"  Vor dem alten Haus spielen heute mehrere fröhliche Kinder.  ","location":{"start_offset":10}}]`),
	}
	evidence, ok := BestSentenceEvidence(candidate)
	assert.True(t, ok)
	assert.Equal(t, source, evidence.Sentence)
}

func TestScoreSentenceQuality(t *testing.T) {
	tests := []struct {
		name, sentence, target, reason string
		location                       int64
		accepted                       bool
	}{
		{"long contextual", "Vor dem alten Haus spielen heute mehrere fröhliche Kinder, während ihre Eltern im sonnigen Garten gemeinsam das Abendessen vorbereiten.", "Haus", "usable length", 42, true},
		{"too short", "Altes Haus.", "Haus", "too short or fragmented", 42, false},
		{"too long", "Das Haus " + strings.Repeat("steht weit außerhalb der alten Stadt ", 9) + "still.", "Haus", "too long", 42, false},
		{"missing target", "Vor dem alten Gebäude spielen heute mehrere fröhliche Kinder.", "Haus", "target not present as a word", 42, false},
		{"fragmented boundary", "Vor dem alten Haus spielen heute mehrere Kinder", "Haus", "incomplete sentence boundaries", 42, false},
		{"contents", "Inhaltsverzeichnis: Das Haus und seine lange Geschichte ..... 12.", "Haus", "structural noise or boilerplate", 42, false},
		{"bibliography", "Bibliography: Das Haus in der europäischen Literatur.", "Haus", "structural noise or boilerplate", 42, false},
		{"numbered list", "12. Das Haus steht oberhalb des alten Dorfes.", "Haus", "structural noise or boilerplate", 42, false},
		{"chapter heading", "Kapitel 3: Das Haus und seine lange Geschichte.", "Haus", "structural noise or boilerplate", 42, false},
		{"citation density", "Das Haus wird bei Müller [1999] und Schmidt [2004] ausführlich beschrieben.", "Haus", "structural noise or boilerplate", 42, false},
		{"extraction anomaly", "Das Haus Haus Haus Haus steht heute am See.", "Haus", "structural noise or boilerplate", 42, false},
		{"boilerplate", "All rights reserved for this edition of Haus und Garten.", "Haus", "structural noise or boilerplate", 42, false},
		{"invalid location", "Vor dem alten Haus spielen heute mehrere fröhliche Kinder.", "Haus", "invalid source location", -1, false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := ScoreSentenceQuality(tc.sentence, tc.target, tc.location)
			assert.Equal(t, tc.accepted, got.Accepted)
			assert.True(t, contains(got.Reasons, tc.reason), "quality=%+v", got)
		})
	}
}

func TestBestSentenceEvidenceRanksAllReferences(t *testing.T) {
	candidate := domain.SelectionCandidate{
		CorpusID:       "corpus-1",
		CanonicalLemma: "haus",
		ObservedForms:  []byte(`["Haus"]`),
		SentenceReferences: []byte(`[
			{"sentence_index":1,"text":"Inhaltsverzeichnis: Das Haus und seine Geschichte ..... 12.","location":{"start_offset":10}},
			{"sentence_index":2,"text":"Vor dem alten Haus spielen heute mehrere fröhliche Kinder im Garten.","location":{"start_offset":80}}
		]`),
	}
	got, ok := BestSentenceEvidence(candidate)
	assert.True(t, ok)
	assert.True(t, got.Quality.Accepted)
	assert.Equal(t, "corpus-1", got.CorpusID)
	assert.Equal(t, int64(80), got.FirstEncounter)
	assert.Equal(t, int64(2), got.SentenceOrdinal)
	assert.Equal(t, "Haus", got.Target)
	assert.True(t, strings.HasPrefix(got.Sentence, "Vor dem"))
}

func TestBestSentenceEvidenceUsesWordTargetsAndStableSourceOrder(t *testing.T) {
	candidate := domain.SelectionCandidate{
		CanonicalLemma: "Haus",
		ObservedForms:  []byte(`["Haus"]`),
		SentenceReferences: []byte(`[
			{"sentence_index":9,"text":"Dieses Haus steht seit vielen Jahren ruhig am See.","location":{"start_offset":90}},
			{"sentence_index":2,"text":"Unser Haus steht seit vielen Jahren ruhig am See.","location":{"start_offset":20}},
			{"sentence_index":1,"text":"Das Hausboot liegt seit vielen Jahren ruhig am See.","location":{"start_offset":10}}
		]`),
	}
	first, ok := BestSentenceEvidence(candidate)
	second, okAgain := BestSentenceEvidence(candidate)
	assert.True(t, ok)
	assert.True(t, okAgain)
	assert.Equal(t, "Unser Haus steht seit vielen Jahren ruhig am See.", first.Sentence)
	assert.Equal(t, second.Sentence, first.Sentence)
	assert.Equal(t, second.Target, first.Target)
	assert.Equal(t, second.FirstEncounter, first.FirstEncounter)
	assert.Equal(t, second.Quality.Accepted, first.Quality.Accepted)
	assert.Equal(t, second.Quality.Score, first.Quality.Score)
	assert.Equal(t, strings.Join(second.Quality.Reasons, "\x00"), strings.Join(first.Quality.Reasons, "\x00"))
}

func TestBestSentenceEvidenceRanksAcceptedReferencesByGradualGDEXScore(t *testing.T) {
	candidate := domain.SelectionCandidate{
		CorpusID:       "corpus-1",
		Language:       "de",
		CanonicalLemma: "see",
		ObservedForms:  []byte(`["See"]`),
		SentenceReferences: []byte(`[
			{"sentence_index":0,"text":"marginal","location":{"start_offset":10}},
			{"sentence_index":1,"text":"good","location":{"start_offset":100}}
		]`),
	}
	sentences := map[int64]analyzer.Sentence{
		0: {
			Text: "Anna steht heute am alten See.",
			Tokens: []analyzer.Token{
				{Surface: "Anna", UPOS: "PROPN", Dependency: "nsubj", Head: 1},
				{Surface: "steht", UPOS: "VERB", Dependency: "root", Head: 1, Morphology: map[string]string{"VerbForm": "Fin"}},
				{Surface: "heute", UPOS: "ADV", Dependency: "advmod", Head: 1},
				{Surface: "am", UPOS: "ADP", Dependency: "case", Head: 5},
				{Surface: "alten", UPOS: "ADJ", Dependency: "amod", Head: 5},
				{Surface: "See", UPOS: "NOUN", Dependency: "obl", Head: 1},
			},
		},
		1: {
			Text: "Der See liegt neben dem alten Haus.",
			Tokens: []analyzer.Token{
				{Surface: "Der", UPOS: "DET", Dependency: "det", Head: 1},
				{Surface: "See", UPOS: "NOUN", Dependency: "nsubj", Head: 2},
				{Surface: "liegt", UPOS: "VERB", Dependency: "root", Head: 2, Morphology: map[string]string{"VerbForm": "Fin"}},
				{Surface: "neben", UPOS: "ADP", Dependency: "case", Head: 6},
				{Surface: "dem", UPOS: "DET", Dependency: "det", Head: 6},
				{Surface: "alten", UPOS: "ADJ", Dependency: "amod", Head: 6},
				{Surface: "Haus", UPOS: "NOUN", Dependency: "obl", Head: 2},
			},
		},
	}

	got, ok := BestSentenceEvidenceFromCorpus(candidate, sentences)
	require.True(t, ok)
	assert.Equal(t, "corpus-1", got.CorpusID)
	assert.Equal(t, sentences[1].Text, got.Sentence)
	assert.Equal(t, int64(100), got.FirstEncounter)
	assert.Equal(t, int64(1), got.SentenceOrdinal)
	assert.Greater(t, got.Quality.GDEXScore, float64(0))
}

func TestBestSentenceEvidenceUsesGenericGreekQualityPath(t *testing.T) {
	candidate := domain.SelectionCandidate{
		CorpusID: "greek-corpus", Language: "el", CanonicalLemma: "σπίτι", ObservedForms: []byte(`["σπίτι"]`),
		SentenceReferences: []byte(`[{"sentence_index":0,"text":"Στο μεγάλο σπίτι ο Νίκος διαβάζει κάθε βράδυ.","location":{"start_offset":10}}]`),
	}
	sentences := map[int64]analyzer.Sentence{0: {
		Text: "Στο μεγάλο σπίτι ο Νίκος διαβάζει κάθε βράδυ.",
		Tokens: []analyzer.Token{
			{Surface: "Στο", UPOS: "ADP", Dependency: "case", Head: 2},
			{Surface: "μεγάλο", UPOS: "ADJ", Dependency: "amod", Head: 2},
			{Surface: "σπίτι", UPOS: "NOUN", Dependency: "nsubj", Head: 5},
			{Surface: "ο", UPOS: "DET", Dependency: "det", Head: 4},
			{Surface: "Νίκος", UPOS: "PROPN", Dependency: "nsubj", Head: 5},
			{Surface: "διαβάζει", UPOS: "VERB", Dependency: "root", Head: 5, Morphology: map[string]string{"VerbForm": "Fin"}},
			{Surface: "κάθε", UPOS: "DET", Dependency: "det", Head: 7},
			{Surface: "βράδυ", UPOS: "NOUN", Dependency: "obl", Head: 5},
		},
	}}
	got, ok := BestSentenceEvidenceFromCorpus(candidate, sentences)
	require.True(t, ok)
	assert.True(t, got.Quality.Accepted)
	assert.Zero(t, got.Quality.GDEXScore)
	assert.NotContains(t, got.Quality.Reasons, "deictic context")
	assert.NotContains(t, got.Quality.Reasons, "named-entity density")
}

func TestBestSentenceEvidenceUsesSourceOrderWhenGradualScoresTie(t *testing.T) {
	candidate := domain.SelectionCandidate{
		CanonicalLemma: "haus",
		ObservedForms:  []byte(`["Haus"]`),
		SentenceReferences: []byte(`[
			{"sentence_index":1,"text":"Das Haus steht heute noch am alten See.","location":{"start_offset":20}},
			{"sentence_index":0,"text":"Das Haus steht heute am alten See.","location":{"start_offset":10}}
		]`),
	}

	got, ok := BestSentenceEvidence(candidate)
	require.True(t, ok)
	assert.Equal(t, "Das Haus steht heute am alten See.", got.Sentence)
	assert.Equal(t, int64(10), got.FirstEncounter)
}

func TestManifestRecordsPersistedGDEXDiagnostics(t *testing.T) {
	manifest := newManifest("alice", "Book", []Entry{{
		Language: "de", CanonicalLemma: "see", UPOS: "NOUN", Sentence: "Anna steht heute hier am See.", TargetWord: "See", FirstEncounter: 10,
		SentenceTokens: []analyzer.Token{
			{Surface: "Anna", UPOS: "PROPN", Dependency: "nsubj", Head: 1},
			{Surface: "steht", UPOS: "VERB", Dependency: "root", Head: 1, Morphology: map[string]string{"VerbForm": "Fin"}},
			{Surface: "heute", UPOS: "ADV", Dependency: "advmod", Head: 1},
			{Surface: "hier", UPOS: "ADV", Dependency: "advmod", Head: 1},
			{Surface: "am", UPOS: "ADP", Dependency: "case", Head: 5},
			{Surface: "See", UPOS: "NOUN", Dependency: "obl", Head: 1},
		},
	}})
	snapshot := manifest.Snapshot()
	require.Len(t, snapshot.Items, 1)
	assert.True(t, snapshot.Items[0].Quality.Accepted)
	assert.Greater(t, snapshot.Items[0].Quality.GDEXScore, float64(0))
	assert.Contains(t, snapshot.Items[0].Quality.Reasons, "deictic context")
	assert.Contains(t, snapshot.Items[0].Quality.Reasons, "named-entity density")
	_, err := snapshot.Digest()
	assert.NoError(t, err)
}

func contains(values []string, want string) bool {
	return slices.Contains(values, want)
}
