package cardexport

import (
	"archive/zip"
	"bytes"
	"context"
	"database/sql"
	"encoding/csv"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
	"testing"

	"github.com/justin-hayes/mouseion/internal/analyzer"
	"github.com/justin-hayes/mouseion/internal/dictionary"
	"github.com/justin-hayes/mouseion/internal/domain"
	"github.com/justin-hayes/mouseion/internal/enrichment"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

type memoryStore struct {
	entries      []Entry
	candidates   []domain.SelectionCandidate
	known        []domain.KnownVocabulary
	history      []domain.GeneratedVocabulary
	reserved     []domain.DeckPreparationVocabulary
	generated    []Note
	bookID       string
	historyCalls map[string]int
}

type scopedMemoryStore struct {
	*memoryStore
	corpusID string
}

type persistedMemoryStore struct {
	*memoryStore
	sentences map[int64]analyzer.Sentence
	listCalls int
}

func (s *persistedMemoryStore) ListCorpusSentences(_ context.Context, _ string, _ string, _ []int64) (map[int64]analyzer.Sentence, error) {
	s.listCalls++
	return s.sentences, nil
}

func (s *scopedMemoryStore) GetSourceMaterial(context.Context, string, string) (domain.SourceMaterial, error) {
	return domain.SourceMaterial{ID: s.bookID, Title: "Scoped Book"}, nil
}

func (s *scopedMemoryStore) GetCorpusForAnalysis(context.Context, string, string) (domain.Corpus, error) {
	return domain.Corpus{ID: s.corpusID, SourceMaterialID: s.bookID, AnalysisRunID: "run-1", Status: "complete"}, nil
}

func (s *scopedMemoryStore) ListSelectionCandidatesForCorpus(ctx context.Context, owner, corpusID string) ([]domain.SelectionCandidate, error) {
	var result []domain.SelectionCandidate
	for _, candidate := range s.candidates {
		if candidate.OwnerID == "" || candidate.OwnerID == owner {
			if candidate.CorpusID == corpusID {
				result = append(result, candidate)
			}
		}
	}
	return result, nil
}

func (s *scopedMemoryStore) GetCoverageEntryForCorpus(ctx context.Context, owner, _ string, candidate domain.SelectionCandidate) (Entry, error) {
	return s.GetCoverageEntryForBook(ctx, owner, s.bookID, candidate)
}

func TestDownloadFilenameAndDeckName(t *testing.T) {
	assert.Equal(t, "Mouseion::de::Das archaische Griechenland", DeckName("de", "Das archaische Griechenland"))
	assert.Equal(t, "Über_.._Buch___.apkg", DownloadFilename(`  Über/../Buch:*?  `))
	a, b := DownloadFilename("../"), DownloadFilename("../")
	assert.Equal(t, b, a)
	assert.True(t, strings.HasPrefix(a, "mouseion-deck-"))
	assert.True(t, strings.HasSuffix(a, ".apkg"))
}

func TestDeckDescriptionRetainsDictionaryAttribution(t *testing.T) {
	assert.Equal(t, "Generated by Mouseion", deckDescription([]Entry{{Language: "de"}}))
	assert.Equal(t, "Generated by Mouseion\n\n"+dictionary.AttributionNotice, deckDescription([]Entry{{DictionaryProviderVersion: "dump=2026-09-14"}}))
}

func TestBoldTargetEscapesHTMLAndClozeSyntax(t *testing.T) {
	got, err := BoldTarget(`<b>Das {{falsche}} Haus & mehr.</b>`, "Haus")
	require.NoError(t, err)
	want := `&lt;b&gt;Das &#123;&#123;falsche&#125;&#125; <b>Haus</b> &amp; mehr.&lt;/b&gt;`
	assert.Equal(t, want, got)
}

func TestAnkiPackageContractAndStableIDs(t *testing.T) {
	note := Note{Key: DedupKey("de", "haus", "NOUN", "alice"), Identity: strings.Repeat("a", 64), Text: "Das <b>Haus</b> ist heute sehr ruhig.", Article: "das", Lemma: "Haus", Plural: "Häuser", IPA: "/haʊ̯s/", PrincipalParts: "geht · ging · gegangen", POS: "NOUN", Gloss: "home", English: "house", EnglishSentence: "The house is very quiet today.", BookTitle: "Das archaische Griechenland", Tags: []string{"Mouseion", "lang::de", "pos::NOUN", "source::Das_archaische_Griechenland"}}
	missingSentenceTranslation := note
	missingSentenceTranslation.Key = DedupKey("de", "baum", "NOUN", "alice")
	missingSentenceTranslation.Identity = strings.Repeat("b", 64)
	missingSentenceTranslation.Article = "der"
	missingSentenceTranslation.Lemma = "Baum"
	missingSentenceTranslation.English = "tree"
	missingSentenceTranslation.EnglishSentence = ""
	deckName := DeckName("de", note.BookTitle)
	notes := []Note{note, missingSentenceTranslation}
	a, err := renderAPKG(deckName, notes, dictionary.AttributionNotice)
	require.NoError(t, err)
	b, err := renderAPKG(deckName, notes, dictionary.AttributionNotice)
	require.NoError(t, err)
	assert.True(t, bytes.Equal(a, b), "package bytes are not deterministic")
	zr, err := zip.NewReader(bytes.NewReader(a), int64(len(a)))
	require.NoError(t, err)
	members := map[string]*zip.File{}
	for _, f := range zr.File {
		members[f.Name] = f
	}
	require.NotNil(t, members["collection.anki2"])
	require.NotNil(t, members["media"])
	assert.Len(t, members, 2)
	media, _ := members["media"].Open()
	var mediaMap map[string]string
	err = json.NewDecoder(media).Decode(&mediaMap)
	require.NoError(t, err)
	assert.Empty(t, mediaMap)
	dbReader, _ := members["collection.anki2"].Open()
	dbBytes, _ := io.ReadAll(dbReader)
	dbPath := t.TempDir() + "/collection.anki2"
	err = os.WriteFile(dbPath, dbBytes, 0o600)
	require.NoError(t, err)
	db, err := sql.Open("sqlite", dbPath)
	require.NoError(t, err)
	defer db.Close()
	var modelsJSON, decksJSON, dconfJSON string
	err = db.QueryRow(`SELECT models,decks,dconf FROM col`).Scan(&modelsJSON, &decksJSON, &dconfJSON)
	require.NoError(t, err)
	assert.Contains(t, modelsJSON, `"name":"Mouseion Vocab Recognition"`)
	assert.Contains(t, modelsJSON, `"qfmt":"{{Text}}"`)
	assert.Contains(t, modelsJSON, `\u003cdiv class=\"gloss meaning-block\"\u003e{{Gloss}}\u003c/div\u003e`)
	assert.Contains(t, modelsJSON, `\u003cdiv class=\"sentence contextual-translation\"\u003e{{EnglishSentence}}\u003c/div\u003e`)
	assert.NotContains(t, modelsJSON, `\u003cdiv class=\"english\"\u003e{{English}}\u003c/div\u003e`)
	assert.NotContains(t, modelsJSON, `{{Morph}}`)
	assert.NotContains(t, modelsJSON, `{{SourceSentence}}`)
	assert.NotContains(t, strings.ToLower(modelsJSON), "cloze")
	assert.NotContains(t, modelsJSON, `"name":"Morph"`)
	assert.Contains(t, decksJSON, deckName)
	assert.Contains(t, decksJSON, dictionary.AttributionNotice)
	var models map[string]struct {
		Fields []struct {
			Name string `json:"name"`
		} `json:"flds"`
	}
	err = json.Unmarshal([]byte(modelsJSON), &models)
	require.NoError(t, err)
	gotNames := make([]string, 0, len(fieldNames))
	for _, model := range models {
		for _, field := range model.Fields {
			gotNames = append(gotNames, field.Name)
		}
	}
	assert.Equal(t, strings.Join(fieldNames, ","), strings.Join(gotNames, ","))
	assertLegacyCollectionContract(t, modelsJSON, decksJSON, dconfJSON, deckName)
	var noteID, cardCount, checksum int64
	var fields, tags, sortField string
	err = db.QueryRow(`SELECT id,flds,tags,sfld,csum FROM notes WHERE guid=?`, note.Key[:20]).Scan(&noteID, &fields, &tags, &sortField, &checksum)
	require.NoError(t, err)
	serializedFields := strings.Split(fields, "\x1f")
	assert.Equal(t, stableID("note|"+note.Key), noteID)
	require.Len(t, serializedFields, 12)
	assert.Equal(t, note.Identity, serializedFields[0])
	assert.Equal(t, note.Text, serializedFields[1])
	assert.Equal(t, note.Article, serializedFields[2])
	assert.Equal(t, note.Lemma, serializedFields[3])
	assert.Equal(t, note.Plural, serializedFields[4])
	assert.Equal(t, note.IPA, serializedFields[5])
	assert.Equal(t, note.PrincipalParts, serializedFields[6])
	assert.Equal(t, note.POS, serializedFields[7])
	assert.Equal(t, note.Gloss, serializedFields[8])
	assert.Equal(t, note.English, serializedFields[9])
	assert.Equal(t, note.EnglishSentence, serializedFields[10])
	assert.Equal(t, note.BookTitle, serializedFields[11])
	assert.Equal(t, note.Identity, sortField)
	assert.Equal(t, fieldChecksum(note.Identity), checksum)
	assert.Contains(t, tags, " Mouseion ")
	assert.NotContains(t, strings.ToLower(tags), "leech")
	err = db.QueryRow(`SELECT flds FROM notes WHERE guid=?`, missingSentenceTranslation.Key[:20]).Scan(&fields)
	require.NoError(t, err)
	serializedFields = strings.Split(fields, "\x1f")
	require.Len(t, serializedFields, 12)
	assert.Equal(t, "", serializedFields[10])
	var distinctSortFields int64
	err = db.QueryRow(`SELECT count(DISTINCT sfld) FROM notes`).Scan(&distinctSortFields)
	require.NoError(t, err)
	assert.Equal(t, int64(2), distinctSortFields)
	err = db.QueryRow(`SELECT count(*) FROM cards`).Scan(&cardCount)
	require.NoError(t, err)
	assert.Equal(t, int64(2), cardCount)
}

func TestAnkiCardPresentationHierarchy(t *testing.T) {
	note := Note{Key: strings.Repeat("a", 64), Identity: strings.Repeat("b", 64), Text: "Das <b>Haus</b> ist ruhig.", Lemma: "Haus", Plural: "Häuser", IPA: "/haʊ̯s/", PrincipalParts: "geht · ging · gegangen", POS: "NOUN", Gloss: "house", EnglishSentence: "The house is quiet."}
	apkg, err := renderAPKG("Mouseion::de::Preview", []Note{note}, "")
	require.NoError(t, err)

	modelsJSON := collectionColumn(t, apkg, "models")
	var models map[string]struct {
		Templates []struct {
			Answer string `json:"afmt"`
		} `json:"tmpls"`
		CSS string `json:"css"`
	}
	require.NoError(t, json.Unmarshal([]byte(modelsJSON), &models))
	require.Len(t, models, 1)
	var model struct {
		Templates []struct {
			Answer string `json:"afmt"`
		} `json:"tmpls"`
		CSS string `json:"css"`
	}
	for _, candidate := range models {
		model = candidate
	}
	require.Len(t, model.Templates, 1)
	answer := model.Templates[0].Answer
	assert.Contains(t, answer, `<div class="card-back">`)
	assert.Contains(t, answer, `<div class="headword-line">`)
	assert.Contains(t, answer, `<strong class="headword">{{Lemma}}</strong>`)
	assert.Contains(t, answer, `<div class="gloss meaning-block">{{Gloss}}</div>`)
	assert.Contains(t, answer, `<div class="sentence contextual-translation">{{EnglishSentence}}</div>`)
	assert.NotContains(t, answer, `{{English}}`)
	assert.Less(t, strings.Index(answer, `class="headword-line"`), strings.Index(answer, `class="gloss meaning-block"`))
	assert.Less(t, strings.Index(answer, `class="gloss meaning-block"`), strings.Index(answer, `class="sentence contextual-translation"`))

	for _, token := range []string{
		"--mouseion-color-surface",
		"--mouseion-color-surface-raised",
		"--mouseion-color-text",
		"--mouseion-color-text-muted",
		"--mouseion-color-border",
		"--mouseion-font-reading",
		".headword",
		".inflection",
		".nightMode",
		"--mouseion-space-5",
		"--mouseion-width-reading",
	} {
		assert.Contains(t, model.CSS, token)
	}
	for _, token := range []string{
		"--mouseion-color-border: #b8c5cc",
		"--mouseion-color-accent-hover: #173f87",
		"--mouseion-color-text-muted: #aebdc5",
		"--mouseion-font-application: \"Avenir Next\", Avenir, \"Gill Sans\", \"Segoe UI\", sans-serif",
		"--mouseion-font-reading: \"Palatino Linotype\", Palatino, \"Book Antiqua\", Georgia, serif",
	} {
		assert.Contains(t, model.CSS, token)
	}
}

func TestCardPresentationPreviewIsFrozen(t *testing.T) {
	preview, err := os.ReadFile("testdata/recognition_card_preview.html")
	require.NoError(t, err)
	previewHTML := string(preview)
	assert.Contains(t, previewHTML, `href="../templates/recognition_card.css"`)
	assert.Contains(t, previewHTML, `content="../templates/recognition_card_back.html"`)
	assert.Contains(t, previewHTML, `class="card-back"`)
	assert.Contains(t, previewHTML, `class="card nightMode"`)
	assert.Contains(t, previewHTML, `class="gloss meaning-block"`)
	assert.NotContains(t, previewHTML, `class="english"`)
}

func collectionColumn(t *testing.T, apkg []byte, column string) string {
	t.Helper()
	zr, err := zip.NewReader(bytes.NewReader(apkg), int64(len(apkg)))
	require.NoError(t, err)
	for _, member := range zr.File {
		if member.Name != "collection.anki2" {
			continue
		}
		reader, openErr := member.Open()
		require.NoError(t, openErr)
		dbBytes, readErr := io.ReadAll(reader)
		require.NoError(t, readErr)
		require.NoError(t, reader.Close())
		dbPath := t.TempDir() + "/collection.anki2"
		require.NoError(t, os.WriteFile(dbPath, dbBytes, 0o600))
		db, openErr := sql.Open("sqlite", dbPath)
		require.NoError(t, openErr)
		defer db.Close()
		var value string
		require.NoError(t, db.QueryRow("SELECT "+column+" FROM col").Scan(&value))
		return value
	}
	t.Fatalf("missing collection.anki2")
	return ""
}

func assertLegacyCollectionContract(t *testing.T, modelsJSON, decksJSON, dconfJSON, deckName string) {
	t.Helper()
	fixture, err := os.ReadFile("testdata/legacy_collection_contract.json")
	require.NoError(t, err)
	var contract map[string]map[string]string
	err = json.Unmarshal(fixture, &contract)
	require.NoError(t, err)

	collections := map[string]string{"models": modelsJSON, "decks": decksJSON, "dconf": dconfJSON}
	for collectionName, encoded := range collections {
		decoder := json.NewDecoder(strings.NewReader(encoded))
		decoder.UseNumber()
		var entries map[string]map[string]any
		err = decoder.Decode(&entries)
		require.NoError(t, err, "decode %s JSON: %v\n%s", collectionName, err, encoded)
		assert.Len(t, entries, 1)
		for key, entry := range entries {
			assertJSONShape(t, collectionName, entry, contract[collectionName])
			if id, ok := entry["id"].(json.Number); ok {
				value, numberErr := id.Int64()
				require.NoError(t, numberErr, "%s id %q is not JSON-safe: %v", collectionName, id, numberErr)
				assert.LessOrEqual(t, value, int64(1<<53-1), "%s id %q is not JSON-safe", collectionName, id)
				if collectionName != "dconf" {
					assert.Equal(t, id.String(), key, "%s key %q does not match id %q", collectionName, key, id)
				}
			}
			if collectionName == "decks" {
				assert.Equal(t, deckName, entry["name"], "deck name")
			}
		}
	}
}

func assertJSONShape(t *testing.T, name string, value map[string]any, shape map[string]string) {
	t.Helper()
	for field, wantType := range shape {
		got, ok := value[field]
		if !ok {
			assert.Fail(t, "%s missing required field %q", name, field)
			continue
		}
		valid := false
		switch wantType {
		case "string":
			_, valid = got.(string)
		case "number":
			_, valid = got.(json.Number)
		case "boolean":
			_, valid = got.(bool)
		case "object":
			_, valid = got.(map[string]any)
		case "array":
			_, valid = got.([]any)
		case "number_pair":
			pair, isArray := got.([]any)
			valid = isArray && len(pair) == 2
			for _, item := range pair {
				_, isNumber := item.(json.Number)
				valid = valid && isNumber
			}
		}
		if !valid {
			assert.Fail(t, "%s field %q = %#v, want %s", name, field, got, wantType)
		}
	}
}

func (m *memoryStore) ListGeneratedVocabulary(_ context.Context, owner, language string) ([]domain.GeneratedVocabulary, error) {
	if m.historyCalls == nil {
		m.historyCalls = make(map[string]int)
	}
	m.historyCalls[language]++
	var out []domain.GeneratedVocabulary
	for _, word := range m.history {
		if word.OwnerID == owner && word.Language == language {
			out = append(out, word)
		}
	}
	return out, nil
}

func (m *memoryStore) ListUnattachedGeneratedVocabulary(ctx context.Context, owner, language string) ([]domain.GeneratedVocabulary, error) {
	return m.ListGeneratedVocabulary(ctx, owner, language)
}

func (m *memoryStore) ListReservedVocabulary(_ context.Context, owner, language string) ([]domain.DeckPreparationVocabulary, error) {
	var result []domain.DeckPreparationVocabulary
	for _, word := range m.reserved {
		if word.OwnerID == owner && word.Language == language {
			result = append(result, word)
		}
	}
	return result, nil
}

func (m *memoryStore) ListSelectionCandidatesForBook(_ context.Context, _ string, bookID string) ([]domain.SelectionCandidate, error) {
	if bookID != m.bookID {
		return nil, nil
	}
	return append([]domain.SelectionCandidate(nil), m.candidates...), nil
}
func (m *memoryStore) ListKnownVocabulary(_ context.Context, _ string, language string) ([]domain.KnownVocabulary, error) {
	var out []domain.KnownVocabulary
	for _, word := range m.known {
		if word.Language == language {
			out = append(out, word)
		}
	}
	return out, nil
}
func (m *memoryStore) GetCoverageEntryForBook(_ context.Context, owner, _ string, candidate domain.SelectionCandidate) (Entry, error) {
	for _, entry := range m.entries {
		if entry.OwnerID == owner && entry.Language == candidate.Language && entry.CanonicalLemma == candidate.CanonicalLemma && entry.UPOS == candidate.UPOS {
			return entry, nil
		}
	}
	return Entry{}, errors.New("missing entry")
}

func (m *memoryStore) RecordGeneratedForBook(_ context.Context, owner, bookID, _ string, e Entry, n Note) error {
	if owner != e.OwnerID {
		return ErrInvalidInput
	}
	if bookID != m.bookID {
		return ErrInvalidInput
	}
	m.generated = append(m.generated, n)
	return nil
}

func TestDedupKeyStableAndOwnerScoped(t *testing.T) {
	a := DedupKey("de", "Haus", "NOUN", "alice")
	assert.Len(t, a, 64)
	for _, b := range []string{DedupKey("de", "Haus", "NOUN", "bob"), DedupKey("fr", "Haus", "NOUN", "alice"), DedupKey("de", "haus", "NOUN", "alice"), DedupKey("de", "Haus", "VERB", "alice")} {
		assert.NotEqual(t, b, a, "distinct identity produced same key")
	}
}

func TestCardIdentityIsDeterministicCardSpecificAndOwnerScoped(t *testing.T) {
	entry := Entry{Language: "de", CanonicalLemma: "gut", UPOS: "ADJ", TargetWord: "die Besten›", Sentence: "Heute sah sie ‹die Besten› und lächelte freundlich.", SourceDocument: "Book", FirstEncounter: 42}
	identity := CardIdentity("alice", entry)
	cleanEntry := entry
	cleanEntry.TargetWord = "die Besten"
	assert.Len(t, identity, 64)
	assert.Equal(t, identity, CardIdentity("alice", entry), "identity is unstable across equivalent legacy target forms")
	assert.Equal(t, identity, CardIdentity("alice", cleanEntry), "identity is unstable across equivalent legacy target forms")
	variants := []struct {
		owner string
		entry Entry
	}{
		{owner: "bob", entry: entry},
		{owner: "alice", entry: func() Entry {
			value := entry
			value.CanonicalLemma = "die"
			value.UPOS = "DET"
			value.TargetWord = "‹die"
			return value
		}()},
		{owner: "alice", entry: func() Entry { value := entry; value.FirstEncounter++; return value }()},
	}
	for _, variant := range variants {
		assert.NotEqual(t, identity, CardIdentity(variant.owner, variant.entry), "distinct card inputs collided: %+v", variant)
	}
}

func TestHighlightEnglishTargetSupportsSafeUniqueMultiwordMatches(t *testing.T) {
	tests := []struct{ name, translation, target, want string }{
		{"single", "The house is large.", "house", "The <b>house</b> is large."},
		{"multiword", "She visited the old house yesterday.", "old house", "She visited the <b>old house</b> yesterday."},
		{"missing", "The building is large.", "house", "The building is large."},
		{"ambiguous", "The house is beside another house.", "house", "The house is beside another house."},
		{"boundary", "The houses are large.", "house", "The houses are large."},
		{"markup", "The <script>alert(1)</script> house.", "house", "The &lt;script&gt;alert(1)&lt;/script&gt; <b>house</b>."},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			assert.Equal(t, test.want, HighlightEnglishTarget(test.translation, test.target))
		})
	}
}

func TestBoldTargetUsesOriginalUnicodeByteOffsets(t *testing.T) {
	for _, test := range []struct {
		sentence, target, want string
	}{
		{sentence: "ẞ Haus ist heute sehr groß.", target: "Haus", want: "ẞ <b>Haus</b> ist heute sehr groß."},
		{sentence: "Das ẞ steht heute dort ruhig.", target: "ß", want: "Das <b>ẞ</b> steht heute dort ruhig."},
		{sentence: "K Haus ist heute sehr groß.", target: "Haus", want: "K <b>Haus</b> ist heute sehr groß."},
		{sentence: "Heute blieb die Souveränität› vollständig erhalten.", target: "Souveränität›", want: "Heute blieb die <b>Souveränität</b>› vollständig erhalten."},
		{sentence: "Heute sah sie ‹die Besten› dort.", target: "die Besten›", want: "Heute sah sie ‹<b>die Besten</b>› dort."},
		{sentence: "Heute sah sie ‹die Besten› dort.", target: "‹die", want: "Heute sah sie ‹<b>die</b> Besten› dort."},
		{sentence: "Oggi O'Neill-like arriva insieme agli amici.", target: "O'Neill-like", want: "Oggi <b>O&#39;Neill-like</b> arriva insieme agli amici."},
	} {
		got, err := BoldTarget(test.sentence, test.target)
		require.NoError(t, err)
		assert.Equal(t, test.want, got)
	}
}

func TestAnkiCardSchemaRegressionContract(t *testing.T) {
	assert.Equal(t, []string{"Identity", "Text", "Article", "Lemma", "Plural", "IPA", "PrincipalParts", "POS", "Gloss", "English", "EnglishSentence", "BookTitle"}, fieldNames)
	model := modelMetadata(1, 2)
	modelFields := model["flds"].([]map[string]any)
	modelNames := make([]string, len(modelFields))
	for i, field := range modelFields {
		modelNames[i] = field["name"].(string)
	}
	assert.Equal(t, fieldNames, modelNames)
	assert.False(t, containsString(modelNames, "Morph"))
	assert.False(t, containsString(modelNames, "SourceSentence"))
	template := model["tmpls"].([]any)[0].(map[string]any)["afmt"].(string)
	assert.Contains(t, template, `{{#Article}}<span class="article">{{Article}}</span><span class="article-space" data-article="{{Article}}"> </span>{{/Article}}<strong class="headword">{{Lemma}}</strong>`)
	assert.Contains(t, template, `{{#Plural}} <span class="inflection plural">(Pl. {{Plural}})</span>{{/Plural}}`)
	assert.Contains(t, template, `{{#IPA}} <span class="inflection pronunciation">{{IPA}}</span>{{/IPA}}`)
	assert.Contains(t, template, `{{#PrincipalParts}} <span class="inflection principal-parts">{{PrincipalParts}}</span>{{/PrincipalParts}}`)
	assert.Contains(t, template, `<div class="gloss meaning-block">{{Gloss}}</div>`)
	assert.Contains(t, template, `<div class="sentence contextual-translation">{{EnglishSentence}}</div>`)
	assert.NotContains(t, template, `<div class="english">{{English}}</div>`)
	assert.Contains(t, model["css"].(string), `.article-space[data-article="l'"]`)
	assert.Contains(t, model["css"].(string), `.inflection`)
	assert.Contains(t, model["css"].(string), `--mouseion-color-text-muted`)
	assert.NotContains(t, model["css"].(string), ".english")
	assert.NotContains(t, template, "{{Morph}}")
	assert.NotContains(t, template, "{{SourceSentence}}")

	german, err := makeNote("alice", Entry{Language: "de", CanonicalLemma: "haus", UPOS: "NOUN", Sentence: "Dieses Haus steht heute neben dem Bahnhof.", TargetWord: "Haus", Morphology: `{"Gender":"Neut"}`})
	require.NoError(t, err)
	assert.Equal(t, "das", german.Article)
	assert.True(t, strings.HasPrefix(german.BackExtra, "das Haus\n"), "German noun article = %q, back = %q", german.Article, german.BackExtra)
	italian, err := makeNote("alice", Entry{Language: "it", CanonicalLemma: "portare", UPOS: "VERB", Sentence: "Domani Lucia porterà il pane fresco alla famiglia.", TargetWord: "porterà", Morphology: `{"Mood":"Ind"}`})
	require.NoError(t, err)
	assert.Equal(t, "", italian.Article)

	path := t.TempDir() + "/collection.anki2"
	db, err := sql.Open("sqlite", path)
	require.NoError(t, err)
	defer db.Close()
	first := german
	first.Key = strings.Repeat("a", 64)
	first.Identity = "identity-a"
	second := german
	second.Key = strings.Repeat("b", 64)
	second.Identity = "identity-b"
	second.Article = "der"
	err = writeCollection(db, "deck", []Note{first, second}, "Generated by Mouseion")
	require.NoError(t, err)
	rows, err := db.Query(`SELECT flds,sfld,csum FROM notes`)
	require.NoError(t, err)
	defer rows.Close()
	seen := make(map[string]bool, 2)
	for rows.Next() {
		var fields, sortField string
		var checksum int64
		err := rows.Scan(&fields, &sortField, &checksum)
		require.NoError(t, err)
		serialized := strings.Split(fields, "\x1f")
		require.Len(t, serialized, 12)
		assert.Equal(t, sortField, serialized[0])
		assert.Equal(t, fieldChecksum(sortField), checksum)
		assert.True(t, sortField == first.Identity || sortField == second.Identity, "fields=%q sfld=%q csum=%d", fields, sortField, checksum)
		seen[sortField] = true
	}
	require.NoError(t, rows.Err())
	assert.Len(t, seen, 2, "distinct identity sort fields = %v", seen)
}

func TestMakeNoteRetainsEnglishFieldButOmitsItFromPersistedBack(t *testing.T) {
	note, err := makeNote("alice", Entry{
		Language: "de", CanonicalLemma: "haus", UPOS: "NOUN",
		Sentence: "Dieses Haus steht heute neben dem Bahnhof.", TargetWord: "Haus",
		Gloss: "dwelling", Translation: "lemma translation",
		SentenceTranslation: "This house stands beside the station.",
	})
	require.NoError(t, err)
	assert.Equal(t, "lemma translation", note.English)
	assert.Equal(t, "Haus\nNOUN\ndwelling\nThis house stands beside the station.", note.BackExtra)
}

// TestAnkiNewCardOrderFollowsTextPosition pins the deck configuration so new
// cards are introduced in the order they appear in the source text. The export
// writes notes sorted by first encounter and binds each card's Anki position
// (due) to that index; the deck config must use ordered new-card presentation
// (order: 0 = "in order added") rather than randomizing (order: 1), or the
// text-order position encoded in due is discarded at review time.
func TestAnkiNewCardOrderFollowsTextPosition(t *testing.T) {
	notes := []Note{
		{Key: DedupKey("de", "wort", "NOUN", "alice"), Identity: "i1", Text: "Erstes <b>Wort</b>.", Article: "das", Lemma: "Wort", POS: "NOUN", English: "word", EnglishSentence: "First word.", BookTitle: "Buch"},
		{Key: DedupKey("de", "haus", "NOUN", "alice"), Identity: "i2", Text: "Zweites <b>Haus</b>.", Article: "das", Lemma: "Haus", POS: "NOUN", English: "house", EnglishSentence: "Second house.", BookTitle: "Buch"},
		{Key: DedupKey("de", "buch", "NOUN", "alice"), Identity: "i3", Text: "Drittes <b>Buch</b>.", Article: "das", Lemma: "Buch", POS: "NOUN", English: "book", EnglishSentence: "Third book.", BookTitle: "Buch"},
	}
	a, err := renderAPKG(DeckName("de", "Buch"), notes, "Generated by Mouseion")
	require.NoError(t, err)
	zr, err := zip.NewReader(bytes.NewReader(a), int64(len(a)))
	require.NoError(t, err)
	var db *sql.DB
	for _, f := range zr.File {
		if f.Name != "collection.anki2" {
			continue
		}
		rc, _ := f.Open()
		dbBytes, _ := io.ReadAll(rc)
		rc.Close()
		path := t.TempDir() + "/collection.anki2"
		err = os.WriteFile(path, dbBytes, 0o600)
		require.NoError(t, err)
		db, err = sql.Open("sqlite", path)
		require.NoError(t, err)
		break
	}
	defer db.Close()
	var dconfJSON string
	err = db.QueryRow(`SELECT dconf FROM col`).Scan(&dconfJSON)
	require.NoError(t, err)
	// dconf serializes a single keyed deck config named "1".
	var configs map[string]struct {
		New struct {
			Order float64 `json:"order"`
		} `json:"new"`
	}
	err = json.Unmarshal([]byte(dconfJSON), &configs)
	require.NoError(t, err)
	var order float64
	for _, cfg := range configs {
		order = cfg.New.Order
	}
	assert.Equal(t, float64(0), order, "new.card order = %v, want 0 (in order added), so text-position due is honored", order)
	// Every card's position must ascend 1..N, bound to text order.
	rows, err := db.Query(`SELECT due FROM cards ORDER BY due`)
	require.NoError(t, err)
	defer rows.Close()
	var dues []int64
	for rows.Next() {
		var due int64
		err = rows.Scan(&due)
		require.NoError(t, err)
		dues = append(dues, due)
	}
	assert.Len(t, dues, len(notes), "card due positions = %v, want len %d", dues, len(notes))
	for i, due := range dues {
		assert.Equal(t, int64(i+1), due, "card due positions = %v, want 1..%d in text order", dues, len(notes))
	}
}

func containsString(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}

func TestRenderTSVEscapesAndOrdersFields(t *testing.T) {
	n := Note{Key: "key", Identity: "identity", Text: "Grüße <b>Welt</b>", Article: "die", Lemma: "Welt", IPA: "/vɛlt/", PrincipalParts: "geht · ging · gegangen", POS: "NOUN", English: "world", EnglishSentence: "Hello world.", BookTitle: "My Book", Tags: []string{"Mouseion", "lang::de", "source::My_Book"}}
	got, err := RenderTSV([]Note{n}, "")
	require.NoError(t, err)
	r := csv.NewReader(strings.NewReader(got))
	r.Comma = '\t'
	rows, err := r.ReadAll()
	require.NoError(t, err)
	require.Len(t, rows, 1)
	require.Len(t, rows[0], 13)
	assert.Equal(t, strings.Join(noteFields(n), "\x1f"), strings.Join(rows[0][:12], "\x1f"))
	assert.Equal(t, "Mouseion lang::de source::My_Book", rows[0][12])
}

func TestRenderTSVIncludesDictionaryAttributionAsComment(t *testing.T) {
	got, err := RenderTSV([]Note{{Identity: "identity"}}, dictionary.AttributionNotice)
	require.NoError(t, err)
	assert.Contains(t, got, "# "+dictionary.AttributionNotice+"\n")

	r := csv.NewReader(strings.NewReader(got))
	r.Comma = '\t'
	r.Comment = '#'
	rows, err := r.ReadAll()
	require.NoError(t, err)
	assert.Equal(t, [][]string{{"identity", "", "", "", "", "", "", "", "", "", "", "", ""}}, rows)
}

func TestEscapeFieldCannotInjectAnkiFieldSeparator(t *testing.T) {
	got := escapeField("safe\x1finjected")
	assert.NotContains(t, got, "\x1f")
	assert.Equal(t, "safe&#31;injected", got)
}

func TestMakeNoteFormatsLemmaWithoutChangingTargetOrIdentity(t *testing.T) {
	entry := Entry{
		Language: "de", CanonicalLemma: "haus", UPOS: "NOUN",
		Sentence: "Die Häuser sind alt.", TargetWord: "Häuser", Morphology: `{"Gender":"Neut","Number":"Plur"}`,
	}
	note, err := makeNote("alice", entry)
	require.NoError(t, err)
	assert.Contains(t, note.Text, "<b>Häuser</b>")
	assert.Equal(t, "das", note.Article)
	assert.Equal(t, "Haus", note.Lemma)
	assert.True(t, strings.HasPrefix(note.BackExtra, "das Haus\n"))
	assert.Equal(t, DedupKey("de", "haus", "NOUN", "alice"), note.Key, "note key = %q, want canonical identity key %q", note.Key, DedupKey("de", "haus", "NOUN", "alice"))
}

func TestMakeNoteDerivesNounArticleFromMorphology(t *testing.T) {
	for _, test := range []struct {
		name, language, lemma, sentence, target, morphology, wantArticle, wantLemma string
	}{
		{name: "feminine ignores declined context", language: "de", sentence: "Bei der Iteration wurde das Ergebnis erneut geprüft.", target: "Iteration", morphology: `{"Case":"Dat","Gender":"Fem","Number":"Sing"}`, wantArticle: "die", wantLemma: "Iteration"},
		{name: "neuter without context article", language: "de", sentence: "Dieses Ruderblatt wurde gestern sorgfältig ausgetauscht.", target: "Ruderblatt", morphology: `{"Gender":"Neut","Number":"Sing"}`, wantArticle: "das", wantLemma: "Ruderblatt"},
		{name: "masculine singular", language: "de", sentence: "Dort steht ein Baum seit vielen Jahren.", target: "Baum", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "der", wantLemma: "Baum"},
		{name: "plural inflection uses lemma gender", language: "de", lemma: "haus", sentence: "Viele Häuser stehen seit Jahren am See.", target: "Häuser", morphology: `{"Gender":"Neut","Number":"Plur"}`, wantArticle: "das", wantLemma: "Haus"},
		{name: "plural only without gender", language: "de", lemma: "eltern", sentence: "Meine Eltern wohnen seit Jahren am See.", target: "Eltern", morphology: `{"Number":"Plur"}`, wantArticle: "die", wantLemma: "Eltern"},
		{name: "gender sufficient when number missing", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `{"Gender":"Neut"}`, wantArticle: "das", wantLemma: "Haus"},
		{name: "missing gender and singular number", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `{"Number":"Sing"}`, wantLemma: "Haus"},
		{name: "consistent gender across number variants", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `[{"Gender":"Neut","Number":"Sing"},{"Gender":"Neut","Number":"Plur"}]`, wantArticle: "das", wantLemma: "Haus"},
		{name: "ambiguous gender variants", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `[{"Gender":"Neut","Number":"Sing"},{"Gender":"Masc","Number":"Sing"}]`, wantLemma: "Haus"},
		{name: "malformed morphology", language: "de", sentence: "Dieses Haus steht seit Jahren am See.", target: "Haus", morphology: `{`, wantLemma: "Haus"},
		{name: "German plural article form falls back to masculine gender", language: "de", sentence: "Viele Gauner wurden verhaftet.", target: "Gauner", morphology: `{"Article":"Gauner","Gender":"Masc","Number":"Plur"}`, wantArticle: "der", wantLemma: "Gauner"},
		{name: "German plural article form falls back to feminine gender", language: "de", sentence: "Feigheiten werden nicht belohnt.", target: "Feigheiten", morphology: `{"Article":"Feigheiten","Gender":"Fem","Number":"Plur"}`, wantArticle: "die", wantLemma: "Feigheiten"},
		{name: "German accusative article falls back to masculine gender", language: "de", sentence: "Ich sehe den Gauner.", target: "Gauner", morphology: `{"Article":"den","Gender":"Masc","Number":"Sing"}`, wantArticle: "der", wantLemma: "Gauner"},
		{name: "German dative article falls back to masculine gender", language: "de", sentence: "Ich helfe dem Gauner.", target: "Gauner", morphology: `{"Article":"dem","Gender":"Masc","Number":"Sing"}`, wantArticle: "der", wantLemma: "Gauner"},
		{name: "German genitive article falls back to neuter gender", language: "de", sentence: "Die Farbe des Hauses ist schön.", target: "Hauses", morphology: `{"Article":"des","Gender":"Neut","Number":"Sing"}`, wantArticle: "das", wantLemma: "Hauses"},
		{name: "Italian plural article falls back to masculine gender", language: "it", sentence: "I libri sono sul tavolo.", target: "libri", morphology: `{"Article":"dei","Gender":"Masc","Number":"Plur"}`, wantArticle: "il", wantLemma: "libri"},
		{name: "Italian prepositional article falls back to masculine gender", language: "it", sentence: "Parlo del libro.", target: "libro", morphology: `{"Article":"del","Gender":"Masc","Number":"Sing"}`, wantArticle: "il", wantLemma: "libro"},
		{name: "Italian prepositional article falls back to feminine gender", language: "it", sentence: "Parlo della casa.", target: "casa", morphology: `{"Article":"della","Gender":"Fem","Number":"Sing"}`, wantArticle: "la", wantLemma: "casa"},
		{name: "Italian feminine", language: "it", sentence: "La casa è ancora molto grande oggi.", target: "casa", morphology: `{"Gender":"Fem","Number":"Sing"}`, wantArticle: "la", wantLemma: "casa"},
		{name: "Italian masculine", language: "it", sentence: "Il pane è ancora fresco oggi.", target: "pane", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "il", wantLemma: "pane"},
		{name: "Italian impure s masculine", language: "it", sentence: "Lo studente legge ancora oggi.", target: "studente", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "lo", wantLemma: "studente"},
		{name: "Italian z masculine", language: "it", sentence: "Lo zaino è ancora pieno oggi.", target: "zaino", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "lo", wantLemma: "zaino"},
		{name: "Italian masculine vowel", language: "it", sentence: "Uomo, vieni ancora qui oggi.", target: "uomo", morphology: `{"Gender":"Masc","Number":"Sing"}`, wantArticle: "l&#39;", wantLemma: "uomo"},
		{name: "Italian feminine vowel", language: "it", sentence: "Amica, vieni ancora qui oggi.", target: "amica", morphology: `{"Gender":"Fem","Number":"Sing"}`, wantArticle: "l&#39;", wantLemma: "amica"},
		{name: "Italian language tag with region", language: "it-IT", sentence: "La casa è ancora molto grande oggi.", target: "casa", morphology: `{"Gender":"Fem","Number":"Sing"}`, wantArticle: "la", wantLemma: "casa"},
	} {
		t.Run(test.name, func(t *testing.T) {
			lemma := test.lemma
			if lemma == "" {
				lemma = strings.ToLower(test.target)
			}
			note, err := makeNote("alice", Entry{Language: test.language, CanonicalLemma: lemma, UPOS: "NOUN", Sentence: test.sentence, TargetWord: test.target, Morphology: test.morphology})
			require.NoError(t, err)
			assert.Equal(t, test.wantArticle, note.Article)
			assert.Equal(t, test.wantLemma, note.Lemma)
		})
	}
}

func TestBuildCoverageAddsItalianDefiniteArticleToNoun(t *testing.T) {
	store := &memoryStore{bookID: "libro"}
	store.candidates = []domain.SelectionCandidate{{
		Language: "it", CanonicalLemma: "casa", UPOS: "NOUN", OccurrenceCount: 3,
		ObservedForms:      []byte(`["casa"]`),
		SentenceReferences: []byte(`[{"sentence_index":0,"text":"La casa è ancora molto grande oggi.","location":{"start_offset":0}}]`),
	}}
	store.entries = []Entry{{OwnerID: "alice", Language: "it", CanonicalLemma: "casa", UPOS: "NOUN", Morphology: `{"Gender":"Fem","Number":"Sing"}`, SourceDocument: "Il viaggio"}}

	artifact, err := NewService(store).BuildCoverage(context.Background(), "alice", "libro")
	require.NoError(t, err)
	require.Len(t, artifact.Generated, 1)
	assert.Equal(t, "la", artifact.Generated[0].Note.Article)
	assert.True(t, strings.HasPrefix(artifact.Generated[0].Note.BackExtra, "la casa\n"))
}

func TestMakeNoteJoinsItalianElidedArticleWithoutSpace(t *testing.T) {
	note, err := makeNote("alice", Entry{
		Language: "it", CanonicalLemma: "uomo", UPOS: "NOUN",
		Sentence: "Uomo, vieni ancora qui oggi.", TargetWord: "uomo", Morphology: `{"Gender":"Masc","Number":"Sing"}`,
	})
	require.NoError(t, err)
	assert.Equal(t, "l&#39;", note.Article)
	assert.True(t, strings.HasPrefix(note.BackExtra, "l&#39;uomo\n"))
}

func TestBestSentenceEvidencePreservesCompleteSourceText(t *testing.T) {
	const source = "  Vor dem alten Haus spielen heute mehrere fröhliche Kinder.  "
	candidate := domain.SelectionCandidate{
		CanonicalLemma:     "haus",
		ObservedForms:      []byte(`["Haus"]`),
		SentenceReferences: []byte(`[{"text":"  Vor dem alten Haus spielen heute mehrere fröhliche Kinder.  ","location":{"start_offset":10}}]`),
	}
	evidence, ok := BestSentenceEvidence(candidate)
	assert.True(t, ok)
	assert.Equal(t, source, evidence.Sentence)
}

func TestLongContextIsRejectedWithoutShorteningOrAlternativeFront(t *testing.T) {
	longSentence := "Das Haus steht am Rand, während die Kinder im großen Garten spielen und ihre Eltern " + strings.Repeat("das Abendessen vorbereiten und über den nächsten Tag sprechen ", 8) + "weitergehen."
	entry := Entry{
		OwnerID: "alice", Language: "de", CanonicalLemma: "haus", UPOS: "NOUN", Sentence: longSentence,
		TargetWord: "Haus", Translation: "house",
		SentenceTranslation: "The house stands at the edge while the children play.", SourceDocument: "Book",
		FirstEncounter: 12,
	}
	store := &memoryStore{bookID: "book", candidates: []domain.SelectionCandidate{{
		OwnerID: "alice", Language: "de", CanonicalLemma: "haus", UPOS: "NOUN", OccurrenceCount: 3,
		ObservedForms: []byte(`["Haus"]`), SentenceReferences: []byte(`[{"text":` + jsonString(longSentence) + `,"location":{"start_offset":12}}]`),
	}}, entries: []Entry{entry}}

	artifact, err := NewService(store).BuildCoverage(context.Background(), "alice", "book")
	require.NoError(t, err)
	assert.Equal(t, 0, artifact.Count)
	assert.Equal(t, 1, artifact.Completeness.QualityOmitted)
	require.Len(t, artifact.Omitted, 1)
	assert.True(t, contains(artifact.Omitted[0].Reasons, "too long"))
	assert.NotContains(t, artifact.TSV, longSentence, "long source was rendered despite deterministic quality gate")
}

func TestPreparedArtifactCoversRecognitionContractAcrossAPKGAndTSV(t *testing.T) {
	const owner, bookID, sourceDocument = "alice", "book", "German rollout book"
	longSentence := "Das Haus steht am Rand," + strings.Repeat(" während die Kinder im großen Garten spielen", 12) + "."
	punctuationSentence := "Heute sah sie ‹die Besten› und lächelte freundlich."
	fixtures := []struct {
		lemma, upos, target, sentence, morphology, plural, ipa, principalParts, translation, sentenceTranslation string
		firstEncounter                                                                                           int64
	}{
		{lemma: "die", upos: "DET", target: "‹die", sentence: punctuationSentence, translation: "the", sentenceTranslation: "Today she saw the best and smiled kindly.", firstEncounter: 10},
		{lemma: "gut", upos: "ADJ", target: "die Besten›", sentence: punctuationSentence, translation: "good", sentenceTranslation: "Today she saw the best and smiled kindly.", firstEncounter: 20},
		{lemma: "souveränität", upos: "NOUN", target: "Souveränität›", sentence: "Über Souveränität› sprach die Professorin gestern sehr ausführlich.", morphology: `{"Gender":"Fem","Number":"Sing"}`, translation: "sovereignty", sentenceTranslation: "The professor spoke about sovereignty in detail yesterday.", firstEncounter: 25},
		{lemma: "geleiten", upos: "VERB", target: "geleitet", sentence: "Nausikaa hat ihn geleitet und danach den Weg beschrieben.", ipa: "/ɡəˈlaɪ̯tən/", principalParts: "geleitet · geleitete · geleitet", translation: "to guide", sentenceTranslation: "Nausikaa guided him and then described the path.", firstEncounter: 30},
		{lemma: "buch", upos: "NOUN", target: "Buch", sentence: "Ich lese heute das Buch und lerne daraus viel.", morphology: `{"Gender":"Neut","Number":"Sing"}`, plural: "Bücher", translation: "book", sentenceTranslation: "Today I read the book and learn a lot from it.", firstEncounter: 40},
		{lemma: "iteration", upos: "NOUN", target: "Iteration", sentence: "Bei der Iteration wurde das Ergebnis erneut sorgfältig geprüft.", morphology: `{"Case":"Dat","Gender":"Fem","Number":"Sing"}`, translation: "iteration", sentenceTranslation: "The result was carefully checked again during the iteration.", firstEncounter: 42},
		{lemma: "ruderblatt", upos: "NOUN", target: "Ruderblatt", sentence: "Dieses Ruderblatt wurde gestern in der Werkstatt sorgfältig ausgetauscht.", morphology: `{"Gender":"Neut","Number":"Sing"}`, translation: "rudder blade", sentenceTranslation: "This rudder blade was carefully replaced in the workshop yesterday.", firstEncounter: 44},
		{lemma: "besuchen", upos: "VERB", target: "besucht", sentence: "Morgen besucht Anna ihre Klasse im Museum und lernt viel.", ipa: "/bəˈzuːχən/", translation: "to visit", sentenceTranslation: "Tomorrow Anna visits her class at the museum and learns a lot.", firstEncounter: 50},
		{lemma: "haus", upos: "NOUN", target: "Haus", sentence: longSentence, morphology: `{"Gender":"Neut","Number":"Sing"}`, translation: "house", sentenceTranslation: "The house stands at the edge while the children play in the garden.", firstEncounter: 60},
	}
	store := &memoryStore{bookID: bookID}
	for _, fixture := range fixtures {
		store.candidates = append(store.candidates, domain.SelectionCandidate{
			OwnerID: owner, Language: "de", CanonicalLemma: fixture.lemma, UPOS: fixture.upos, OccurrenceCount: 3,
			ObservedForms:      []byte("[" + jsonString(fixture.target) + "]"),
			SentenceReferences: []byte("[{\"sentence_index\":0,\"text\":" + jsonString(fixture.sentence) + ",\"location\":{\"start_offset\":" + fmt.Sprint(fixture.firstEncounter) + "}}]"),
		})
		store.entries = append(store.entries, Entry{
			OwnerID: owner, Language: "de", CanonicalLemma: fixture.lemma, UPOS: fixture.upos, Sentence: fixture.sentence,
			TargetWord: fixture.target, Plural: fixture.plural, IPA: fixture.ipa, PrincipalParts: fixture.principalParts, Translation: fixture.translation,
			SentenceTranslation: fixture.sentenceTranslation, Morphology: fixture.morphology, SourceDocument: sourceDocument, FirstEncounter: fixture.firstEncounter,
		})
	}

	service := NewService(store)
	first, err := service.BuildCoverage(context.Background(), owner, bookID)
	require.NoError(t, err)
	second, err := service.BuildCoverage(context.Background(), owner, bookID)
	require.NoError(t, err)
	assert.True(t, bytes.Equal(first.APKG, second.APKG), "prepared artifact is not deterministic")
	assert.Equal(t, second.TSV, first.TSV, "prepared artifact is not deterministic")
	assert.Equal(t, len(fixtures)-1, first.Count)
	assert.Len(t, first.Generated, len(fixtures)-1)
	assert.Len(t, first.Omitted, 1)
	assert.Equal(t, Completeness{TotalCards: len(fixtures) - 1, CardsWithEnglish: len(fixtures) - 1, CardsWithEnglishSentence: len(fixtures) - 1, QualityOmitted: 1}, first.Completeness)

	notesByLemma := make(map[string]Note, len(first.Generated))
	for _, generated := range first.Generated {
		notesByLemma[generated.Entry.CanonicalLemma] = generated.Note
		for _, value := range []string{generated.Note.Identity, generated.Note.Text, generated.Note.Article, generated.Note.Lemma, generated.Note.POS, generated.Note.English, generated.Note.EnglishSentence, generated.Note.BookTitle, generated.Note.BackExtra} {
			assert.False(t, strings.Contains(value, "{{c1::") || strings.Contains(value, "geleiten|leiten") || strings.Contains(value, `"Case"`), "legacy or raw analyzer content in note %q: %+v", value, generated.Note)
		}
	}
	assert.Contains(t, notesByLemma["die"].Text, "‹<b>die</b>")
	assert.Contains(t, notesByLemma["gut"].Text, "‹<b>die Besten</b>›")
	assert.Contains(t, notesByLemma["souveränität"].Text, "<b>Souveränität</b>›")
	assert.Equal(t, "geleiten", notesByLemma["geleiten"].Lemma, "pipe lemma leaked or was not normalized")
	assert.Equal(t, "das", notesByLemma["buch"].Article)
	assert.Equal(t, "Buch", notesByLemma["buch"].Lemma)
	assert.Equal(t, "Bücher", notesByLemma["buch"].Plural)
	assert.Equal(t, "/ɡəˈlaɪ̯tən/", notesByLemma["geleiten"].IPA)
	assert.Equal(t, "geleitet · geleitete · geleitet", notesByLemma["geleiten"].PrincipalParts)
	assert.Equal(t, "/bəˈzuːχən/", notesByLemma["besuchen"].IPA)
	assert.Empty(t, notesByLemma["besuchen"].PrincipalParts)
	assert.Equal(t, DedupKey("de", "buch", "NOUN", owner), notesByLemma["buch"].Key)
	assert.Equal(t, "die", notesByLemma["iteration"].Article)
	assert.Equal(t, "Iteration", notesByLemma["iteration"].Lemma)
	assert.True(t, strings.HasPrefix(notesByLemma["iteration"].BackExtra, "die Iteration\n"))
	assert.Equal(t, "das", notesByLemma["ruderblatt"].Article)
	assert.Equal(t, "Ruderblatt", notesByLemma["ruderblatt"].Lemma)
	assert.True(t, strings.HasPrefix(notesByLemma["ruderblatt"].BackExtra, "das Ruderblatt\n"))
	assert.NotEqual(t, notesByLemma["gut"].Identity, notesByLemma["die"].Identity, "different targets in the same sentence share an Identity")
	for _, candidate := range first.EnrichmentCandidates {
		assert.NotEqual(t, "‹die", candidate.TargetWord, "legacy punctuation leaked into enrichment candidate")
		assert.NotEqual(t, "die Besten›", candidate.TargetWord, "legacy punctuation leaked into enrichment candidate")
	}
	_, ok := notesByLemma["haus"]
	assert.False(t, ok, "long source sentence was exported")

	rows, err := readTSV(first.TSV)
	require.NoError(t, err)
	require.Len(t, rows, len(fixtures)-1)
	require.Len(t, rows[0], 13)
	assert.NotContains(t, first.TSV, longSentence)
	assert.Contains(t, first.TSV, "\tNOUN\t")
	assert.NotContains(t, first.TSV, "{{c1::")
	for i, generated := range first.Generated {
		assert.Equal(t, strings.Join(noteFields(generated.Note), "\x1f"), strings.Join(rows[i][:12], "\x1f"), "TSV row %d=%#v note=%#v", i, rows[i], generated.Note)
	}
	modelsJSON, apkgRows := readAPKGNotes(t, first.APKG)
	assert.Len(t, apkgRows, len(fixtures)-1)
	assert.NotContains(t, strings.ToLower(modelsJSON), "cloze")
	assert.NotContains(t, modelsJSON, `"name":"Morph"`)
	assert.NotContains(t, modelsJSON, `{{Morph}}`)
	apkgByLemma := make(map[string][]string, len(apkgRows))
	for _, row := range apkgRows {
		require.Len(t, row, 12)
		assert.NotContains(t, row[1], "{{c1::")
		assert.NotContains(t, row[3], "geleiten|leiten")
		assert.NotContains(t, row[3], `"Case"`)
		apkgByLemma[row[3]] = row
	}
	for _, generated := range first.Generated {
		row, ok := apkgByLemma[generated.Note.Lemma]
		assert.True(t, ok, "APKG row=%#v note=%#v", row, generated.Note)
		assert.Equal(t, strings.Join(noteFields(generated.Note), "\x1f"), strings.Join(row, "\x1f"), "APKG row=%#v note=%#v", row, generated.Note)
	}
}

func TestManifestExactEnrichmentMatchesLegacyRenderAndIsDeterministic(t *testing.T) {
	entries := []Entry{
		{OwnerID: "alice", Language: "de", CanonicalLemma: "haus", UPOS: "noun", Sentence: "Das alte Haus ist überraschend groß.", TargetWord: "Haus", Translation: "stale", SentenceTranslation: "Stale sentence.", SourceDocument: "Book", FirstEncounter: 10},
		{OwnerID: "alice", Language: "de", CanonicalLemma: "baum", UPOS: "NOUN", Sentence: "Der alte Baum trägt heute viele grüne Blätter.", TargetWord: "Baum", Translation: "stale", SentenceTranslation: "Stale sentence.", SourceDocument: "Book", FirstEncounter: 20},
		{OwnerID: "alice", Language: "de", CanonicalLemma: "fragment", UPOS: "NOUN", Sentence: "Fragment.", TargetWord: "Fragment", SourceDocument: "Book", FirstEncounter: 30},
	}
	exactEntries := append([]Entry(nil), entries...)
	exactEntries[0].Translation, exactEntries[0].SentenceTranslation, exactEntries[0].SentenceTranslationTarget = "house", "The old house is surprisingly large.", "old house"
	exactEntries[1].Translation, exactEntries[1].SentenceTranslation, exactEntries[1].SentenceTranslationTarget = "tree", "The old tree has many green leaves today.", "tree"
	service := &Service{}
	want, err := service.render(context.Background(), "alice", "Book", exactEntries)
	require.NoError(t, err)

	manifest := NewManifest("alice", "Book", entries)
	candidates := manifest.EnrichmentCandidates()
	keys := make([]enrichment.CacheKey, len(candidates))
	outcomes := make([]ExactEnrichment, len(candidates))
	for i, candidate := range candidates {
		keys[i] = enrichment.CacheKey{Language: candidate.Language, TargetLanguage: "en", CanonicalLemma: candidate.CanonicalLemma, UPOS: strings.ToUpper(candidate.UPOS), Provider: "llm", ProviderVersion: "2", SentenceHash: enrichment.SentenceHash(candidate.ExampleSentence)}
		provenance := enrichment.Provenance{Provider: "llm", ProviderVersion: "2"}
		outcomes[i] = ExactEnrichment{CacheKey: keys[i], Result: enrichment.Result{
			Candidate:                 candidate,
			Translation:               enrichment.Field[string]{Value: exactEntries[i].Translation, Available: true, Provenance: provenance},
			SentenceTranslation:       enrichment.Field[string]{Value: exactEntries[i].SentenceTranslation, Available: true, Provenance: provenance},
			SentenceTranslationTarget: enrichment.Field[string]{Value: exactEntries[i].SentenceTranslationTarget, Available: true, Provenance: provenance},
		}}
	}
	bound, err := manifest.BindCacheKeys(keys)
	require.NoError(t, err)
	first, err := service.RenderManifest(context.Background(), bound, outcomes)
	require.NoError(t, err)
	second, err := service.RenderManifest(context.Background(), bound, outcomes)
	require.NoError(t, err)
	assert.True(t, bytes.Equal(first.APKG, want.APKG))
	assert.Equal(t, want.TSV, first.TSV)
	assert.Equal(t, want.Completeness, first.Completeness)
	assert.Equal(t, want.Generated, first.Generated)
	assert.True(t, bytes.Equal(first.APKG, second.APKG))
	assert.Equal(t, second.TSV, first.TSV)
	assert.Equal(t, Completeness{TotalCards: 2, CardsWithEnglish: 2, CardsWithEnglishSentence: 2, QualityOmitted: 1}, first.Completeness)
	assert.Len(t, first.Generated, 2)

	// Returned candidates and caller-owned key slices cannot mutate the bound manifest.
	candidates[0].CanonicalLemma = "mutated"
	keys[0].ProviderVersion = "mutated"
	first.Omitted[0].Reasons[0] = "mutated"
	third, err := service.RenderManifest(context.Background(), bound, outcomes)
	require.NoError(t, err)
	assert.Equal(t, first.TSV, third.TSV, "manifest was mutable")
	assert.True(t, bytes.Equal(first.APKG, third.APKG), "manifest was mutable")
	assert.NotEqual(t, "mutated", third.Omitted[0].Reasons[0], "manifest was mutable")
}

func TestManifestRejectsProviderVersionAndSentenceIdentityMismatch(t *testing.T) {
	entry := Entry{OwnerID: "alice", Language: "de", CanonicalLemma: "haus", UPOS: "noun", Sentence: "Das alte Haus ist überraschend groß.", TargetWord: "Haus", SourceDocument: "Book", FirstEncounter: 10}
	manifest := NewManifest("alice", "Book", []Entry{entry})
	candidate := manifest.EnrichmentCandidates()[0]
	key := enrichment.CacheKey{Language: "de", TargetLanguage: "en", CanonicalLemma: "haus", UPOS: "NOUN", Provider: "llm", ProviderVersion: "2", SentenceHash: enrichment.SentenceHash(candidate.ExampleSentence)}
	bound, err := manifest.BindCacheKeys([]enrichment.CacheKey{key})
	require.NoError(t, err)
	provenance := enrichment.Provenance{Provider: "llm", ProviderVersion: "2"}
	result := enrichment.Result{Candidate: candidate, Translation: enrichment.Field[string]{Value: "house", Available: true, Provenance: provenance}}
	wrongVersion := key
	wrongVersion.ProviderVersion = "1"
	_, err = (&Service{}).RenderManifest(context.Background(), bound, []ExactEnrichment{{CacheKey: wrongVersion, Result: result}})
	assert.ErrorIs(t, err, ErrInvalidInput, "provider-version mismatch")
	wrongSentence := key
	wrongSentence.SentenceHash = enrichment.SentenceHash("Dieses andere Haus steht heute am Stadtrand.")
	_, err = manifest.BindCacheKeys([]enrichment.CacheKey{wrongSentence})
	assert.ErrorIs(t, err, ErrInvalidInput, "sentence mismatch")
}

func TestManifestFallbackGlossFillsMissingDictionaryMeaning(t *testing.T) {
	entry := Entry{Language: "de", CanonicalLemma: "haus", UPOS: "NOUN", Sentence: "Das alte Haus ist überraschend groß.", TargetWord: "Haus", DictionaryProviderVersion: "dictionary-v4", SourceDocument: "Book", FirstEncounter: 10}
	manifest := NewManifest("alice", "Book", []Entry{entry})
	candidate := manifest.EnrichmentCandidates()[0]
	key := enrichment.CacheKey{Language: "de", TargetLanguage: "en", CanonicalLemma: candidate.CanonicalLemma, UPOS: "NOUN", Provider: "llm", ProviderVersion: "model-1", DictionaryProviderVersion: "dictionary-v4", SentenceHash: enrichment.SentenceHash(candidate.ExampleSentence)}
	bound, err := manifest.BindCacheKeys([]enrichment.CacheKey{key})
	require.NoError(t, err)
	provenance := enrichment.Provenance{Provider: "llm", ProviderVersion: "model-1"}
	artifact, err := (&Service{}).RenderManifest(context.Background(), bound, []ExactEnrichment{{CacheKey: key, Result: enrichment.Result{
		Candidate:      candidate,
		Translation:    enrichment.Field[string]{Value: "rare word", Available: true, Provenance: provenance},
		SenseSelection: enrichment.Field[[]int]{Value: []int{}, Available: true, Provenance: provenance},
		FallbackGloss:  enrichment.Field[string]{Value: "something uncommon", Available: true, Provenance: provenance},
	}}})
	require.NoError(t, err)
	require.Len(t, artifact.Generated, 1)
	assert.Equal(t, "something uncommon", artifact.Generated[0].Note.Gloss)
	assert.Equal(t, 1, artifact.Completeness.CardsWithFallbackGloss)

	withoutExternal, err := (&Service{}).RenderManifest(context.Background(), bound, []ExactEnrichment{{CacheKey: key, Result: enrichment.Result{Candidate: candidate}}})
	require.NoError(t, err)
	assert.Empty(t, withoutExternal.Generated[0].Note.Gloss)
	assert.Zero(t, withoutExternal.Completeness.CardsWithFallbackGloss)
}

func TestPreparedManifestPreservesSelectionOrderOmissionsAndGeneratedProvenance(t *testing.T) {
	const owner, bookID = "alice", "book"
	fixtures := []struct {
		lemma, sentence string
		first           int64
	}{
		{"baum", "Der alte Baum trägt heute viele grüne Blätter.", 30},
		{"haus", "Das alte Haus ist überraschend groß.", 10},
		{"fragment", "Fragment.", 20},
	}
	store := &memoryStore{bookID: bookID}
	for _, fixture := range fixtures {
		store.candidates = append(store.candidates, domain.SelectionCandidate{
			OwnerID: owner, Language: "de", CanonicalLemma: fixture.lemma, UPOS: "NOUN", OccurrenceCount: 3, FirstEncounter: fixture.first,
			ObservedForms:      []byte("[" + jsonString(strings.Title(fixture.lemma)) + "]"),
			SentenceReferences: []byte("[{\"text\":" + jsonString(fixture.sentence) + ",\"location\":{\"start_offset\":" + fmt.Sprint(fixture.first) + "}}]"),
		})
		store.entries = append(store.entries, Entry{OwnerID: owner, Language: "de", CanonicalLemma: fixture.lemma, UPOS: "NOUN", Sentence: fixture.sentence, TargetWord: strings.Title(fixture.lemma), SourceDocument: "Book", FirstEncounter: fixture.first})
	}
	service := NewService(store)
	legacy, err := service.BuildCoverage(context.Background(), owner, bookID)
	require.NoError(t, err)
	manifest, err := service.PrepareCoverage(context.Background(), owner, bookID)
	require.NoError(t, err)
	prepared, err := service.RenderManifest(context.Background(), manifest, nil)
	require.NoError(t, err)
	assert.True(t, bytes.Equal(prepared.APKG, legacy.APKG))
	assert.Equal(t, legacy.TSV, prepared.TSV)
	assert.Equal(t, legacy.Completeness, prepared.Completeness)
	assert.Equal(t, legacy.Omitted, prepared.Omitted)
	assert.Equal(t, legacy.Generated, prepared.Generated)
	assert.Less(t, strings.Index(prepared.TSV, "Haus"), strings.Index(prepared.TSV, "Baum"))
	assert.Equal(t, 1, prepared.Completeness.QualityOmitted)
	assert.Len(t, prepared.Generated, 2)
}

func readTSV(value string) ([][]string, error) {
	reader := csv.NewReader(strings.NewReader(value))
	reader.Comma = '\t'
	return reader.ReadAll()
}

func readAPKGNotes(t *testing.T, payload []byte) (string, [][]string) {
	t.Helper()
	zr, err := zip.NewReader(bytes.NewReader(payload), int64(len(payload)))
	require.NoError(t, err)
	var collection []byte
	for _, member := range zr.File {
		if member.Name != "collection.anki2" {
			continue
		}
		reader, openErr := member.Open()
		require.NoError(t, openErr)
		collection, err = io.ReadAll(reader)
		_ = reader.Close()
		require.NoError(t, err)
	}
	path := t.TempDir() + "/collection.anki2"
	err = os.WriteFile(path, collection, 0o600)
	require.NoError(t, err)
	db, err := sql.Open("sqlite", path)
	require.NoError(t, err)
	defer db.Close()
	var modelsJSON string
	err = db.QueryRow(`SELECT models FROM col`).Scan(&modelsJSON)
	require.NoError(t, err)
	rows, err := db.Query(`SELECT flds FROM notes`)
	require.NoError(t, err)
	defer rows.Close()
	var fields [][]string
	for rows.Next() {
		var serialized string
		err = rows.Scan(&serialized)
		require.NoError(t, err)
		fields = append(fields, strings.Split(serialized, "\x1f"))
	}
	require.NoError(t, rows.Err())
	return modelsJSON, fields
}

func jsonString(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func TestBuildCoveragePreparesItalianCardWithoutChangingAccents(t *testing.T) {
	store := &memoryStore{bookID: "libro"}
	store.candidates = []domain.SelectionCandidate{{
		Language: "it", CanonicalLemma: "portare", UPOS: "VERB", OccurrenceCount: 3,
		ObservedForms:      []byte(`["porterà"]`),
		SentenceReferences: []byte(`[{"sentence_index":0,"text":"Domani Lucia porterà finalmente il pane fresco alla sua famiglia.","location":{"start_offset":7}}]`),
	}}
	store.entries = []Entry{{OwnerID: "alice", Language: "it", CanonicalLemma: "portare", UPOS: "VERB", Morphology: `{"Mood":"Ind","Tense":"Fut"}`, Translation: "to bring", SentenceTranslation: "Tomorrow Lucia will finally bring fresh bread to her family.", SourceDocument: "Il viaggio"}}

	artifact, err := NewService(store).BuildCoverage(context.Background(), "alice", "libro")
	require.NoError(t, err)
	assert.Equal(t, 1, artifact.Count)
	assert.Equal(t, "Mouseion::it::Il viaggio", artifact.DeckName)
	assert.Equal(t, "Il viaggio.apkg", artifact.Filename)
	require.Len(t, artifact.Generated, 1)
	note := artifact.Generated[0].Note
	assert.Contains(t, note.Text, "<b>porterà</b>")
	assert.Equal(t, "", note.Article)
	assert.Equal(t, "portare", note.Lemma)
	assert.Contains(t, artifact.TSV, "lang::it")
	assertAPKGDeckAndCard(t, artifact.APKG, "Mouseion::it::Il viaggio", "portare", "lang::it")
}

func TestBuildCoverageForAnalysisUsesOnlyItsCorpus(t *testing.T) {
	store := &scopedMemoryStore{memoryStore: &memoryStore{bookID: "libro"}, corpusID: "corpus-scoped"}
	store.candidates = []domain.SelectionCandidate{
		{OwnerID: "alice", CorpusID: "corpus-scoped", Language: "it", CanonicalLemma: "portare", UPOS: "VERB", OccurrenceCount: 3, ObservedForms: []byte(`["porterà"]`), SentenceReferences: []byte(`[{"text":"Domani Lucia porterà finalmente il pane fresco alla sua famiglia.","location":{"start_offset":7}}]`)},
		{OwnerID: "alice", CorpusID: "corpus-other", Language: "it", CanonicalLemma: "sbagliare", UPOS: "VERB", OccurrenceCount: 100, ObservedForms: []byte(`["sbaglia"]`), SentenceReferences: []byte(`[{"text":"Questo candidato appartiene a un altro risultato analizzato.","location":{"start_offset":7}}]`)},
	}
	store.entries = []Entry{{OwnerID: "alice", Language: "it", CanonicalLemma: "portare", UPOS: "VERB", Translation: "to bring", SourceDocument: "Scoped Book"}}

	artifact, err := NewService(store).BuildCoverageForAnalysis(context.Background(), "alice", "run-1")
	require.NoError(t, err)
	assert.Equal(t, 1, artifact.Count)
	require.Len(t, artifact.Generated, 1)
	assert.Equal(t, "portare", artifact.Generated[0].Entry.CanonicalLemma)
}

func assertAPKGDeckAndCard(t *testing.T, payload []byte, deckName, lemma, tag string) {
	t.Helper()
	zr, err := zip.NewReader(bytes.NewReader(payload), int64(len(payload)))
	require.NoError(t, err, "open APKG")
	var collection []byte
	for _, member := range zr.File {
		if member.Name != "collection.anki2" {
			continue
		}
		reader, openErr := member.Open()
		require.NoError(t, openErr, "open APKG collection")
		collection, err = io.ReadAll(reader)
		_ = reader.Close()
		require.NoError(t, err, "read APKG collection")
	}
	require.NotEmpty(t, collection, "APKG has no collection.anki2")
	path := t.TempDir() + "/collection.anki2"
	err = os.WriteFile(path, collection, 0o600)
	require.NoError(t, err)
	db, err := sql.Open("sqlite", path)
	require.NoError(t, err)
	defer db.Close()
	var decks, fields, tags string
	err = db.QueryRow(`SELECT decks FROM col`).Scan(&decks)
	require.NoError(t, err)
	err = db.QueryRow(`SELECT flds,tags FROM notes`).Scan(&fields, &tags)
	require.NoError(t, err)
	assert.Contains(t, decks, `"name":"`+deckName+`"`, "Italian APKG decks=%s fields=%q tags=%q", decks, fields, tags)
	assert.Contains(t, fields, "\x1f"+lemma+"\x1f", "Italian APKG decks=%s fields=%q tags=%q", decks, fields, tags)
	assert.Contains(t, tags, " "+tag+" ", "Italian APKG decks=%s fields=%q tags=%q", decks, fields, tags)
}

func TestCoverageCandidatesExcludesKnownAndGeneratedBeforeCutoff(t *testing.T) {
	otherBook := "other-book"
	store := &memoryStore{known: []domain.KnownVocabulary{{Language: "de", CanonicalLemma: "known", UPOS: "NOUN"}}}
	store.history = []domain.GeneratedVocabulary{
		{OwnerID: "alice", Language: "de", CanonicalLemma: "generated", UPOS: "NOUN", FirstSourceMaterialID: &otherBook},
		{OwnerID: "alice", Language: "de", CanonicalLemma: "legacy", UPOS: "NOUN"},
	}
	candidates := []domain.SelectionCandidate{
		{Language: "de", CanonicalLemma: "known", UPOS: "NOUN", OccurrenceCount: 100},
		{Language: "de", CanonicalLemma: "generated", UPOS: "NOUN", OccurrenceCount: 100},
		{Language: "de", CanonicalLemma: "legacy", UPOS: "NOUN", OccurrenceCount: 100},
		{Language: "de", CanonicalLemma: "one", UPOS: "NOUN", OccurrenceCount: 96},
		{Language: "de", CanonicalLemma: "singleton-a", UPOS: "NOUN", OccurrenceCount: 1},
		{Language: "de", CanonicalLemma: "singleton-b", UPOS: "NOUN", OccurrenceCount: 2},
	}
	got, err := NewService(store).coverageCandidates(context.Background(), "alice", "current-book", candidates)
	require.NoError(t, err)
	require.Len(t, got, 1)
	assert.Equal(t, "one", got[0].CanonicalLemma)
	assert.Equal(t, 1, store.historyCalls["de"], "generated vocabulary loaded %d times", store.historyCalls["de"])
}

func TestCoverageCandidatesAllowsSameBookAndIsolatesOwners(t *testing.T) {
	currentBook := "current-book"
	store := &memoryStore{history: []domain.GeneratedVocabulary{
		{OwnerID: "alice", Language: "de", CanonicalLemma: "same", UPOS: "NOUN", FirstSourceMaterialID: &currentBook},
		{OwnerID: "bob", Language: "de", CanonicalLemma: "bob-word", UPOS: "NOUN"},
	}}
	candidates := []domain.SelectionCandidate{
		{Language: "de", CanonicalLemma: "same", UPOS: "NOUN", OccurrenceCount: 3},
		{Language: "de", CanonicalLemma: "bob-word", UPOS: "NOUN", OccurrenceCount: 3},
	}
	got, err := NewService(store).coverageCandidates(context.Background(), "alice", currentBook, candidates)
	require.NoError(t, err)
	assert.Len(t, got, 2)
}

func TestCoverageCandidatesReservesOnlyCurrentlyStudiedVocabulary(t *testing.T) {
	store := &memoryStore{reserved: []domain.DeckPreparationVocabulary{{OwnerID: "alice", Language: "de", CanonicalLemma: "reserved", UPOS: "VERB"}}}
	candidates := []domain.SelectionCandidate{
		{Language: "de", CanonicalLemma: "reserved", UPOS: "VERB", OccurrenceCount: 10},
		{Language: "de", CanonicalLemma: "released", UPOS: "ADJ", OccurrenceCount: 10},
	}
	got, err := NewService(store).coverageCandidates(context.Background(), "alice", "future-book", candidates)
	require.NoError(t, err)
	require.Len(t, got, 1)
	assert.Equal(t, "released", got[0].CanonicalLemma)
	store.reserved = nil
	got, err = NewService(store).coverageCandidates(context.Background(), "alice", "future-book", candidates)
	require.NoError(t, err)
	assert.Len(t, got, 2)
}

func TestCoverageCandidatesKnownLemmaWildcardAndRareWordExclusions(t *testing.T) {
	store := &memoryStore{known: []domain.KnownVocabulary{{Language: "de", CanonicalLemma: "known"}}}
	candidates := []domain.SelectionCandidate{
		{Language: "de", CanonicalLemma: "known", UPOS: "VERB", OccurrenceCount: 10},
		{Language: "de", CanonicalLemma: "only", UPOS: "NOUN", OccurrenceCount: 1},
	}
	got, err := NewService(store).coverageCandidates(context.Background(), "alice", "book", candidates)
	require.NoError(t, err)
	assert.Empty(t, got)
}

func TestSelectRecurringCandidatesAppliesFrequencyFloor(t *testing.T) {
	assert.Equal(t, 3, defaultDeckMinOccurrences, "default deck minimum occurrences")
	candidates := []domain.SelectionCandidate{
		{Language: "de", CanonicalLemma: "common", UPOS: "NOUN", OccurrenceCount: 4},
		{Language: "de", CanonicalLemma: "boundary", UPOS: "NOUN", OccurrenceCount: 3},
		{Language: "de", CanonicalLemma: "rare-two", UPOS: "NOUN", OccurrenceCount: 2},
		{Language: "de", CanonicalLemma: "rare-one", UPOS: "NOUN", OccurrenceCount: 1},
	}
	got := selectRecurringCandidates(candidates, defaultDeckMinOccurrences)
	want := []string{"common", "boundary"}
	require.Len(t, got, len(want))
	for i, candidate := range got {
		assert.Equal(t, want[i], candidate.CanonicalLemma, "candidate %d = %q, want %q", i, candidate.CanonicalLemma, want[i])
	}
}

func TestSelectRecurringCandidatesReturnsEmptyPoolWhenAllWordsAreRare(t *testing.T) {
	candidates := []domain.SelectionCandidate{
		{Language: "de", CanonicalLemma: "two", UPOS: "NOUN", OccurrenceCount: 2},
		{Language: "de", CanonicalLemma: "one", UPOS: "NOUN", OccurrenceCount: 1},
	}
	assert.Empty(t, selectRecurringCandidates(candidates, defaultDeckMinOccurrences), "selected = %+v, want empty pool", selectRecurringCandidates(candidates, defaultDeckMinOccurrences))
}

func TestScoreSentenceQuality(t *testing.T) {
	tests := []struct {
		name, sentence, target, reason string
		location                       int64
		accepted                       bool
	}{
		{"long contextual", "Vor dem alten Haus spielen heute mehrere fröhliche Kinder, während ihre Eltern im sonnigen Garten gemeinsam das Abendessen vorbereiten.", "Haus", "usable length", 42, true},
		{"too short", "Altes Haus.", "Haus", "too short or fragmented", 42, false},
		{"too long", "Das Haus " + strings.Repeat("steht weit außerhalb der alten Stadt ", 9) + "still.", "Haus", "too long", 42, false},
		{"missing target", "Vor dem alten Gebäude spielen heute mehrere fröhliche Kinder.", "Haus", "target not present as a word", 42, false},
		{"fragmented boundary", "Vor dem alten Haus spielen heute mehrere Kinder", "Haus", "incomplete sentence boundaries", 42, false},
		{"contents", "Inhaltsverzeichnis: Das Haus und seine lange Geschichte ..... 12.", "Haus", "structural noise or boilerplate", 42, false},
		{"bibliography", "Bibliography: Das Haus in der europäischen Literatur.", "Haus", "structural noise or boilerplate", 42, false},
		{"numbered list", "12. Das Haus steht oberhalb des alten Dorfes.", "Haus", "structural noise or boilerplate", 42, false},
		{"chapter heading", "Kapitel 3: Das Haus und seine lange Geschichte.", "Haus", "structural noise or boilerplate", 42, false},
		{"citation density", "Das Haus wird bei Müller [1999] und Schmidt [2004] ausführlich beschrieben.", "Haus", "structural noise or boilerplate", 42, false},
		{"extraction anomaly", "Das Haus Haus Haus Haus steht heute am See.", "Haus", "structural noise or boilerplate", 42, false},
		{"boilerplate", "All rights reserved for this edition of Haus und Garten.", "Haus", "structural noise or boilerplate", 42, false},
		{"invalid location", "Vor dem alten Haus spielen heute mehrere fröhliche Kinder.", "Haus", "invalid source location", -1, false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := ScoreSentenceQuality(tc.sentence, tc.target, tc.location)
			assert.Equal(t, tc.accepted, got.Accepted)
			assert.True(t, contains(got.Reasons, tc.reason), "quality=%+v", got)
		})
	}
}

func TestBestSentenceEvidenceRanksAllReferences(t *testing.T) {
	candidate := domain.SelectionCandidate{
		CanonicalLemma: "haus",
		ObservedForms:  []byte(`["Haus"]`),
		SentenceReferences: []byte(`[
			{"sentence_index":1,"text":"Inhaltsverzeichnis: Das Haus und seine Geschichte ..... 12.","location":{"start_offset":10}},
			{"sentence_index":2,"text":"Vor dem alten Haus spielen heute mehrere fröhliche Kinder im Garten.","location":{"start_offset":80}}
		]`),
	}
	got, ok := BestSentenceEvidence(candidate)
	assert.True(t, ok)
	assert.True(t, got.Quality.Accepted)
	assert.Equal(t, int64(80), got.FirstEncounter)
	assert.Equal(t, "Haus", got.Target)
	assert.True(t, strings.HasPrefix(got.Sentence, "Vor dem"))
}

func TestBestSentenceEvidenceUsesWordTargetsAndStableSourceOrder(t *testing.T) {
	candidate := domain.SelectionCandidate{
		CanonicalLemma: "Haus",
		ObservedForms:  []byte(`["Haus"]`),
		SentenceReferences: []byte(`[
			{"sentence_index":9,"text":"Dieses Haus steht seit vielen Jahren ruhig am See.","location":{"start_offset":90}},
			{"sentence_index":2,"text":"Unser Haus steht seit vielen Jahren ruhig am See.","location":{"start_offset":20}},
			{"sentence_index":1,"text":"Das Hausboot liegt seit vielen Jahren ruhig am See.","location":{"start_offset":10}}
		]`),
	}
	first, ok := BestSentenceEvidence(candidate)
	second, okAgain := BestSentenceEvidence(candidate)
	assert.True(t, ok)
	assert.True(t, okAgain)
	assert.Equal(t, "Unser Haus steht seit vielen Jahren ruhig am See.", first.Sentence)
	assert.Equal(t, second.Sentence, first.Sentence)
	assert.Equal(t, second.Target, first.Target)
	assert.Equal(t, second.FirstEncounter, first.FirstEncounter)
	assert.Equal(t, second.Quality.Accepted, first.Quality.Accepted)
	assert.Equal(t, second.Quality.Score, first.Quality.Score)
	assert.Equal(t, strings.Join(second.Quality.Reasons, "\x00"), strings.Join(first.Quality.Reasons, "\x00"))
}

func TestBestSentenceEvidenceRanksAcceptedReferencesByGradualGDEXScore(t *testing.T) {
	candidate := domain.SelectionCandidate{
		Language:       "de",
		CanonicalLemma: "see",
		ObservedForms:  []byte(`["See"]`),
		SentenceReferences: []byte(`[
			{"sentence_index":0,"text":"marginal","location":{"start_offset":10}},
			{"sentence_index":1,"text":"good","location":{"start_offset":100}}
		]`),
	}
	sentences := map[int64]analyzer.Sentence{
		0: {
			Text: "Anna steht heute am alten See.",
			Tokens: []analyzer.Token{
				{Surface: "Anna", UPOS: "PROPN", Dependency: "nsubj", Head: 1},
				{Surface: "steht", UPOS: "VERB", Dependency: "root", Head: 1, Morphology: map[string]string{"VerbForm": "Fin"}},
				{Surface: "heute", UPOS: "ADV", Dependency: "advmod", Head: 1},
				{Surface: "am", UPOS: "ADP", Dependency: "case", Head: 5},
				{Surface: "alten", UPOS: "ADJ", Dependency: "amod", Head: 5},
				{Surface: "See", UPOS: "NOUN", Dependency: "obl", Head: 1},
			},
		},
		1: {
			Text: "Der See liegt neben dem alten Haus.",
			Tokens: []analyzer.Token{
				{Surface: "Der", UPOS: "DET", Dependency: "det", Head: 1},
				{Surface: "See", UPOS: "NOUN", Dependency: "nsubj", Head: 2},
				{Surface: "liegt", UPOS: "VERB", Dependency: "root", Head: 2, Morphology: map[string]string{"VerbForm": "Fin"}},
				{Surface: "neben", UPOS: "ADP", Dependency: "case", Head: 6},
				{Surface: "dem", UPOS: "DET", Dependency: "det", Head: 6},
				{Surface: "alten", UPOS: "ADJ", Dependency: "amod", Head: 6},
				{Surface: "Haus", UPOS: "NOUN", Dependency: "obl", Head: 2},
			},
		},
	}

	got, ok := BestSentenceEvidenceFromCorpus(candidate, sentences)
	require.True(t, ok)
	assert.Equal(t, sentences[1].Text, got.Sentence)
	assert.Equal(t, int64(100), got.FirstEncounter)
	assert.Greater(t, got.Quality.GDEXScore, float64(0))
}

func TestBestSentenceEvidenceUsesSourceOrderWhenGradualScoresTie(t *testing.T) {
	candidate := domain.SelectionCandidate{
		CanonicalLemma: "haus",
		ObservedForms:  []byte(`["Haus"]`),
		SentenceReferences: []byte(`[
			{"sentence_index":1,"text":"Das Haus steht heute noch am alten See.","location":{"start_offset":20}},
			{"sentence_index":0,"text":"Das Haus steht heute am alten See.","location":{"start_offset":10}}
		]`),
	}

	got, ok := BestSentenceEvidence(candidate)
	require.True(t, ok)
	assert.Equal(t, "Das Haus steht heute am alten See.", got.Sentence)
	assert.Equal(t, int64(10), got.FirstEncounter)
}

func TestExportCoverageOmitsBadEvidenceAndRecordsOnlyAcceptedNotes(t *testing.T) {
	store := &memoryStore{bookID: "book"}
	store.candidates = []domain.SelectionCandidate{
		{Language: "de", CanonicalLemma: "Haus", UPOS: "NOUN", OccurrenceCount: 3, FirstEncounter: 10, ObservedForms: []byte(`["Haus"]`)},
		{Language: "de", CanonicalLemma: "Baum", UPOS: "NOUN", OccurrenceCount: 3, FirstEncounter: 20, ObservedForms: []byte(`["Baum"]`)},
	}
	store.entries = []Entry{
		{OwnerID: "alice", Language: "de", CanonicalLemma: "Haus", UPOS: "NOUN", Sentence: "Haus.", Translation: "house", SourceDocument: "Book", FirstEncounter: 10},
		{OwnerID: "alice", Language: "de", CanonicalLemma: "Baum", UPOS: "NOUN", Sentence: "Unter dem alten Baum warten heute mehrere müde Wanderer.", Translation: "tree", SentenceTranslation: "Several tired hikers are waiting under the old tree today.", SourceDocument: "Book", FirstEncounter: 20},
	}

	artifact, err := NewService(store).ExportCoverage(context.Background(), "alice", "book")
	require.NoError(t, err)
	assert.Equal(t, 1, artifact.Count)
	assert.Equal(t, Completeness{TotalCards: 1, CardsWithEnglish: 1, CardsWithEnglishSentence: 1, QualityOmitted: 1}, artifact.Completeness)
	require.Len(t, artifact.Omitted, 1)
	assert.Equal(t, "Haus", artifact.Omitted[0].CanonicalLemma)
	require.Len(t, artifact.EnrichmentCandidates, 1)
	assert.Equal(t, "Baum", artifact.EnrichmentCandidates[0].CanonicalLemma)
	assert.NotEmpty(t, artifact.EnrichmentCandidates[0].ExampleSentence)
	assert.Len(t, store.generated, 1)
	assert.Contains(t, artifact.TSV, "Baum")
	assert.NotContains(t, artifact.TSV, "Haus")

	// Rejected evidence was not added to generated history, so improved evidence
	// remains eligible on a later export.
	store.entries[0].Sentence = "Vor dem alten Haus spielen heute mehrere fröhliche Kinder."
	artifact, err = NewService(store).ExportCoverage(context.Background(), "alice", "book")
	require.NoError(t, err)
	assert.Equal(t, 2, artifact.Count)
	assert.Equal(t, Completeness{TotalCards: 2, CardsWithEnglish: 2, CardsWithEnglishSentence: 1}, artifact.Completeness)
	assert.Empty(t, artifact.Omitted)
	assert.Len(t, store.generated, 3)
	assert.Contains(t, artifact.TSV, "Haus")
}

func TestExportCoverageUsesPersistedDependenciesForFiniteVerbGate(t *testing.T) {
	const owner, bookID = "alice", "book"
	store := &persistedMemoryStore{
		memoryStore: &memoryStore{bookID: bookID},
		sentences: map[int64]analyzer.Sentence{
			0: {
				Text: "Das Haus liegt am alten See.",
				Tokens: []analyzer.Token{
					{Surface: "Das", UPOS: "DET", Dependency: "det", Head: 1},
					{Surface: "Haus", UPOS: "NOUN", Dependency: "root", Head: 1},
					{Surface: "liegt", UPOS: "NOUN", Dependency: "flat", Head: 1},
					{Surface: "am", UPOS: "ADP", Dependency: "case", Head: 5},
					{Surface: "alten", UPOS: "ADJ", Dependency: "amod", Head: 5},
					{Surface: "See", UPOS: "NOUN", Dependency: "obl", Head: 1},
				},
			},
			1: {
				Text: "Das Haus steht heute am alten See.",
				Tokens: []analyzer.Token{
					{Surface: "Das", UPOS: "DET", Dependency: "det", Head: 2},
					{Surface: "Haus", UPOS: "NOUN", Dependency: "nsubj", Head: 2},
					{Surface: "steht", UPOS: "VERB", Dependency: "root", Head: 2, Morphology: map[string]string{"VerbForm": "Fin"}},
					{Surface: "heute", UPOS: "ADV", Dependency: "advmod", Head: 2},
					{Surface: "am", UPOS: "ADP", Dependency: "case", Head: 6},
					{Surface: "alten", UPOS: "ADJ", Dependency: "amod", Head: 6},
					{Surface: "See", UPOS: "NOUN", Dependency: "obl", Head: 2},
				},
			},
		},
	}
	store.candidates = []domain.SelectionCandidate{
		{OwnerID: owner, CorpusID: "corpus", Language: "de", CanonicalLemma: "haus", UPOS: "NOUN", OccurrenceCount: 3, FirstEncounter: 10, ObservedForms: []byte(`["Haus"]`), SentenceReferences: []byte(`[{"sentence_index":0,"text":"stale text","location":{"start_offset":10}}]`)},
		{OwnerID: owner, CorpusID: "corpus", Language: "de", CanonicalLemma: "see", UPOS: "NOUN", OccurrenceCount: 3, FirstEncounter: 20, ObservedForms: []byte(`["See"]`), SentenceReferences: []byte(`[{"sentence_index":1,"text":"stale text","location":{"start_offset":20}}]`)},
	}
	store.entries = []Entry{
		{OwnerID: owner, Language: "de", CanonicalLemma: "haus", UPOS: "NOUN", SourceDocument: "Book"},
		{OwnerID: owner, Language: "de", CanonicalLemma: "see", UPOS: "NOUN", SourceDocument: "Book"},
	}

	artifact, err := NewService(store).ExportCoverage(context.Background(), owner, bookID)
	require.NoError(t, err)
	assert.Equal(t, 1, artifact.Count)
	assert.Equal(t, 1, store.listCalls, "persisted sentence data should be fetched in one batch")
	require.Len(t, artifact.Omitted, 1)
	assert.Equal(t, "haus", artifact.Omitted[0].CanonicalLemma)
	assert.Contains(t, artifact.Omitted[0].Reasons, reasonNoFiniteVerbAndSubject)
	assert.Contains(t, artifact.TSV, "See")
	assert.NotContains(t, artifact.TSV, "stale text")

	again, err := NewService(store).ExportCoverage(context.Background(), owner, bookID)
	require.NoError(t, err)
	assert.Equal(t, 1, again.Count)
	assert.Len(t, again.Omitted, 1)
	assert.Equal(t, "haus", again.Omitted[0].CanonicalLemma, "the fragment remains eligible after omission")
}

func TestManifestRecordsPersistedGDEXDiagnostics(t *testing.T) {
	manifest := NewManifest("alice", "Book", []Entry{{
		Language: "de", CanonicalLemma: "see", UPOS: "NOUN", Sentence: "Anna steht heute hier am See.", TargetWord: "See", FirstEncounter: 10,
		SentenceTokens: []analyzer.Token{
			{Surface: "Anna", UPOS: "PROPN", Dependency: "nsubj", Head: 1},
			{Surface: "steht", UPOS: "VERB", Dependency: "root", Head: 1, Morphology: map[string]string{"VerbForm": "Fin"}},
			{Surface: "heute", UPOS: "ADV", Dependency: "advmod", Head: 1},
			{Surface: "hier", UPOS: "ADV", Dependency: "advmod", Head: 1},
			{Surface: "am", UPOS: "ADP", Dependency: "case", Head: 5},
			{Surface: "See", UPOS: "NOUN", Dependency: "obl", Head: 1},
		},
	}})
	snapshot := manifest.Snapshot()
	require.Len(t, snapshot.Items, 1)
	assert.True(t, snapshot.Items[0].Quality.Accepted)
	assert.Greater(t, snapshot.Items[0].Quality.GDEXScore, float64(0))
	assert.Contains(t, snapshot.Items[0].Quality.Reasons, "deictic context")
	assert.Contains(t, snapshot.Items[0].Quality.Reasons, "named-entity density")
	_, err := snapshot.Digest()
	assert.NoError(t, err)
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
